### ISSUE TITLE
Doppelte Verwendung von QR Codes

### ISSUE THREAD

**Issue by lieblb** [DatabayAG/ScanAssessment#12]
Hier zwei PDF-Seiten eines insgesamt 9-seitigen Testbogens, bei dem für Seite 3 und Seite 4 offenbar derselbe QR-Code erzeugt wurde (dies lässt sich schon im ursprünglich erzeugten PDF so nachvollziehen):

![urk-scan-3-0-clean](https://cloud.githubusercontent.com/assets/25431384/23068925/d4a309bc-f525-11e6-8549-f411bc2e632c.jpg)

![urk-scan-4-0-clean](https://cloud.githubusercontent.com/assets/25431384/23068931/d9fab95a-f525-11e6-8a8b-6bfc34ca6fbb.jpg)

Dies führt dann leider dazu, dass bei der Analyse, die entsprechenden Analysedateien der einen Seite überschrieben werden:

<img width="944" alt="ui" src="https://cloud.githubusercontent.com/assets/25431384/23068970/f452d6fc-f525-11e6-82da-d75835d0bc89.png">

Hier das Log:

[log.txt](https://github.com/DatabayAG/ScanAssessment/files/783434/log.txt)

**Comment by gvollbach** [comment]
Ok, ja das die Analyse Daten dann überschrieben werden ist klar, ich hab den Fehler auch schon gefunden.

**Comment by gvollbach** [comment]
Sollte behoben sein.
