### ISSUE TITLE
Endlosrekursion in getLeftBorderPosition (u.a.)

### ISSUE THREAD

**Issue by lieblb** [DatabayAG/ScanAssessment#15]
Bei manchen Bildern tritt bei der Analyse eine Endlosrekursion in `getLeftBorderPosition` auf, wobei die drei anderen Funktionen `getRightBorderPosition`, `getBottomBorderPosition` und `getTopBorderPosition` genau betroffen sind. Der Effekt ist, dass die Analysephase nicht terminiert.

Die Rekursion tritt auf im Fall `if(!$border)`, in dem sich die Funktion selbst mit einem erhöhten `$length_multiplier` aufruft. Im Fall der Endlosrekursion wird der Wert von `$length_multiplier` offenbar beliebig groß (ich bisher immer nach mehreren Minuten bei 1600 abgebrochen).

Eine Bedingung gegen einen absoluten Maximalwert, wie z.B. `if(!$border && $length_multiplier < 5)`behebt das Problem für mich, jedoch stellt sich dann hier für mich die Frage, wie das Programm bei einem solchen Abbruch verfahren sollte. Ist eine Erkennung des Bildes dann noch möglich oder das sollte das Bild mit einer Warnung gekennzeichnet werden, dass hier die Erkennung fehlschlug?

Ich frage mich, kurz gesagt, ob ein Error Reporting im UI, das für gescannte Bilder nachvollziehbar Warnungen anzeigt, für diesen Fall notwendig ist.

**Comment by gvollbach** [comment]
Ja darüber war ich auch schon gestolpert, und genau das hatte ich auch schon eingebaut, nur noch nicht gepusht, was ich gerade gemacht habe.

Zu dem zweiten Punkt, ja die Erkennung des Bildes ist immer noch möglich, hier geht es nur um die genauer Checkbox Positionen. Diie "get*BorderPosition" Scans sind kurz gesagt Scanlines, welche eine schnelle Erkennung der genauen Checkbox Position ermöglichen, danach wird überprüft ob man sich im Zentrum einer Checkbox befindet und sollte das nicht der Fall sein wird noch einmal eine Detail Prüfung angestoßen (probeCrossSection), welche noch einmal genauer scannt, allerdings auch Zeit intensiver. Ich hoffe das erklärt die ganze Funktionsweise etwas genauer.

**Comment by lieblb** [comment]
Wunderbar, mit der aktuellen Version keine Hänger mehr.

**Comment by gvollbach** [comment]
Super dann mach ich hier zu.
