### ISSUE TITLE
Erkennung von Matrikelnummermatrix funktioniert nicht

### ISSUE THREAD

**Issue by lieblb** [DatabayAG/ScanAssessment#18]
Siehe z.B. hier:

<img width="409" alt="matrikelnummermatrix" src="https://cloud.githubusercontent.com/assets/25431384/23987907/2dffe33e-0a2c-11e7-897d-1010757a1b69.png">

Kompletter Debug-Export:

[scasExport.zip](https://github.com/DatabayAG/ScanAssessment/files/847109/scasExport.zip)

**Comment by gvollbach** [comment]
Hier hatten wir ja schon am Telefon kurz drüber gesprochen, werde ich mir diese Woche noch einmal anschauen, wo es dort noch klemmt.

**Comment by lieblb** [comment]
Insgesamt sieht die Positionsberechnung jetzt mit `unstable` für meine Begriffe gut aus, weil, wenn ich es richtig verstehe, die Ersterkennung immer irgendwie in der zu erkennenden Checkbox landet. Und das ist, denke ich, der entscheidende Fortschritt.

Nur die Feinsuche hat noch Probleme, dann auch wirklich immer die Ausmaße der Checkbox zu identifizieren.

Hier ein konkretes Beispiel von 2 Seiten:

[scasExport.zip](https://github.com/DatabayAG/ScanAssessment/files/881521/scasExport.zip)

<img width="438" alt="sample1" src="https://cloud.githubusercontent.com/assets/25431384/24495438/6ae95eec-1535-11e7-9c44-49def3cc2a3d.png">

<img width="440" alt="sample2" src="https://cloud.githubusercontent.com/assets/25431384/24495446/7071b648-1535-11e7-82d7-518bc20011c6.png">

**Comment by gvollbach** [comment]
Ja das hatte ich auch schon gesehen, ich vermute ich muss dort die Feinsuche noch etwas nach justieren. Oder den Boxen etwas mehr Platz geben, bin mir noch nicht so ganz sicher was hier besser ist.

**Comment by lieblb** [comment]
Ich denke eine andere Feinsuche wäre der bessere Ansatz, da das auch in anderen Grenzfällen dann bessere Ergebnisse liefert. 

Ein relativ einfacher aber zuverlässiger Ansatz wäre wohl folgender. Gehe vom errechneten Pixel nach rechts, bis ein dunkler Pixel gefunden wird. Suche dann alle zusammenhängenden Pixel von diesem Pixel aus (flood fill). Dann könnte man mit Hilfe einer Metrik (wie der Größe der Bounding Box, oder, wenn man sehr ambitioniert ist, dem durschnittlichen Mindestabstand des nächsten Pixels zu jedem Pixel der Bounding Box) checken, ob das jetzt die Checkbox ist (oder irgendwas, was innerhalb der Checkbox gemalt wurde). Wenn sie es nicht ist, nimmt man irgendeinen rechten Pixel der eben ermittelten zusammenhängenden Pixelgruppe, und wiederholt das Ganze (geht wieder nach rechts, bis man einen Pixel findet, etc.)

Anders gesagt: ich finde, es lohnt sich hier durchaus Überlegungen und Zeit zu investieren, weil das jetzt das letzte Element zu einer wirklich guten Erkennungsgenauigkeit ist.

**Comment by gvollbach** [comment]
Das wird ja schon teilweise so ähnlich gehandhabt in den get*BorderPosition, allerdings etwas simpler weil das an der Stelle nur erstmal ein grober Scan ist, welcher halt an der Stelle wiederum anfällig für Kreuze in der Checkbox ist.
Aber ich werde dort heute Nachmittag wahrscheinlich auch noch mal ein paar Varianten durchspielen.

Beim letzten Punkt stimme ich ihnen natürlich zu, ich bin deshalb auch immer für Vorschläge/Ideen offen.

**Comment by lieblb** [comment]
Der oben beschriebene Algorithmus als Code, nur mal so als Idee (weil ich's mal ausprobieren wollte):

<img width="58" alt="bildschirmfoto 2017-03-30 um 14 28 51" src="https://cloud.githubusercontent.com/assets/25431384/24504118/3dee6f7a-1555-11e7-87be-1ab008c7eb5c.png">

[docker-scancheckbox.zip](https://github.com/DatabayAG/ScanAssessment/files/882248/docker-scancheckbox.zip)

**Comment by gvollbach** [comment]
Ok, vielversprechend. Ich war mal so frei und hab eine quick & dirty Übernahme in das Plugin gemacht zum testen. Läuft halt aktuell zu weit bei ein paar Boxen, aber sie haben das ja nur direkt gegen eine Checkbox getestet. 
![flood_fill_test](https://cloud.githubusercontent.com/assets/10603233/24507625/34433b0c-1561-11e7-91a7-ee22dc6c8acb.png)

Ich pushe mal einen floodfill Branch, dann können sie da auch mal testen.

**Comment by gvollbach** [comment]
So ich hab mal noch etwas umgebaut, die Ergebnisse sind recht gut, allerdings scheint es hier:
![answer_detection](https://cloud.githubusercontent.com/assets/10603233/24540578/1fae3758-15f4-11e7-9490-0edfe41be193.jpg)
zweite Spalte die 5 noch irgendwas schief zu laufen. Es wird aus irgendeinem Grund ein 5 detektiert statt der 4.

**Comment by lieblb** [comment]
Da bin ich grade dran, um solche Fälle noch zu erkennen. Das ist ein bisschen knifflig. Man muss einen Suchbaum durchsuchen.

**Comment by gvollbach** [comment]
Ich habs gerade mal in den master committed, die Tests die ich bisher versucht haben sehen sehr gut aus. Ich hab übrigens zwischenzeitlich dann auch noch mal ein Log-Level Seting in die Plugin Konfiguration nach gezogen.

**Comment by lieblb** [comment]
Ich hab jetzt beim Testen noch zwei Randfälle entdeckt (einer davon wenn die Checkbox an drei oder vier Seiten keinen sauberen Rand hat). Ich probier am Montag noch zwei Sachen aus. Ansonsten hatte ich auch leider auch noch einen Scan, wo die Markerberechnung daneben lag. Auch dazu mehr nächste Woche.

**Comment by gvollbach** [comment]
Ja bei meinen Tests gab es auch ein, zwei Grenzfälle noch. Zu der Markerberechnung, schicken sie mir einfach wieder den Export, dann schau ich mir das genauer an.

**Comment by lieblb** [comment]
Hier nun nochmal ein Scan, bei dem die Originalposition der Marker erheblich horizontal versetzt berechnet wird, und zwar bei Seite 72 (konkret im Debug Export zu finden unter `export/scans/analysed/72/1):

<img width="627" alt="markers" src="https://cloud.githubusercontent.com/assets/25431384/24949361/97db50a8-1f6d-11e7-83c1-a8a5c51bc1b1.png">

[scasExport.zip](https://github.com/DatabayAG/ScanAssessment/files/915957/scasExport.zip)

**Comment by gvollbach** [comment]
Ich hab mir gerade mal die 72 aus ihrem Paket angesehen und analysiert, bei mir sieht das Ergebniss so aus:
![72_1_answer_detection](https://cloud.githubusercontent.com/assets/10603233/25121560/5f3f1356-2422-11e7-8530-d328ac605c89.png)
Das wundert mich gerade etwas, auch die Mittelpunkte sind bei mir nicht so weit verschoben wie bei ihnen. Haben sie sonst noch irgendwas mit den Bildern vorher gemacht?

**Comment by lieblb** [comment]
Äh, nein. Das ist interessant.

**Comment by lieblb** [comment]
Ich arbeite hier unter zwei Docker-Images, und sehe die verschobenen Marker in PHP 5 und PHP 7, konkret:

```
PHP 5.5.38 (cli) (built: Aug 10 2016 21:03:27) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
```

```
PHP 7.1.3 (cli) (built: Mar 17 2017 22:20:51) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

Hier die Dockerfiles:

[Dockerfiles.zip](https://github.com/DatabayAG/ScanAssessment/files/928068/Dockerfiles.zip)

Sehen Sie das irgendwas ungewöhnliches in meinem Setup?

**EDIT** hier ist mal das gesamte docker-compose-setup, das ich benutze:

[ilias5-test.zip](https://github.com/DatabayAG/ScanAssessment/files/928070/ilias5-test.zip)

**Comment by gvollbach** [comment]
Mh, so auf Anhieb eigentlich nicht, zumindest nichts mit dem ich eine Verschiebung bei der Analyse in Verbindung bringen würde, aber ich werde mir das docker Image noch einmal genauer anschauen. Ich arbeite hier lokal mit `PHP 7.0.15-0ubuntu0.16.04.4` und `PHP 5.6.30-7+deb.sury.org~xenial+1`.

**Comment by lieblb** [comment]
In Ihrem Analyse-Log müsste ja dann etwas anderes stehen, als bei mir. Vielleicht ist das ein Ansatz?

**Comment by gvollbach** [comment]
Ja das wäre eine Idee, können sie mir ihren noch einmal zur Verfügung stellen? Ich hänge meins der Vollständigkeit aber auch nochmal hier ran.
[20170418_ilScanAssessment.txt](https://github.com/DatabayAG/ScanAssessment/files/928107/20170418_ilScanAssessment.txt)

**Comment by lieblb** [comment]
[analysis-log.txt](https://github.com/DatabayAG/ScanAssessment/files/928148/analysis-log.txt)

Da ist ziemlich früh ein Unterschied:

Bei mir:

```
web7_1  | 17-04-18 10:24:32 DEBUG (7): Image seems to be rotated (-0.20269541570111). 
web7_1  | 17-04-18 10:24:33 DEBUG (7): Top Left Marker found Start[82, 153], End[121, 198] starting to detect exact position. 
web7_1  | 17-04-18 10:24:33 DEBUG (7): Exact Top Left Marker found at [108.25, 169.65] with length 65.503129696221. 
```

Bei Ihnen:

```
[cj3uh] [2017-04-18 10:23:31.855152] .DEBUG:  Image seems to be rotated (-0.20269541570111).  
[cj3uh] [2017-04-18 10:23:34.048756] .DEBUG:  Top Left Marker found Start[85, 156], End[125, 200] starting to detect exact position.  
[cj3uh] [2017-04-18 10:23:34.049602] .DEBUG:  Exact Top Left Marker found at [109.4, 174] with length 71.357129987129.  ```

**Comment by lieblb** [comment]
Noch ein paar Env-Checks bei mir:

```
root@08b78b5744bb:/var/www/html# php -r 'var_dump(gd_info()["GD Version"]);'
string(26) "bundled (2.1.0 compatible)"
root@08b78b5744bb:/var/www/html# ldconfig -p | grep libjpeg
	libjpeg.so.62 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libjpeg.so.62
	libjpeg.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libjpeg.so
root@08b78b5744bb:/var/www/html# ldconfig -p | grep libpng 
	libpng12.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libpng12.so.0
	libpng12.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libpng12.so.0
	libpng12.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libpng12.so
```

**Comment by gvollbach** [comment]
Das ist in der Tat interessant, vor allem scheint die Abweichung erst nach der ersten Rotation aufzutreten, bis dahin scheint alles noch gleich zu sein.
`string(5) "2.1.1"`

libjpegxr.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libjpegxr.so.0

libjpeg.so.62 (libc6) => /usr/lib/i386-linux-gnu/libjpeg.so.62

libjpeg.so.9 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libjpeg.so.9

libjpeg.so.8 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libjpeg.so.8

libjpeg.so.8 (libc6) => /usr/lib/i386-linux-gnu/libjpeg.so.8

libjpeg.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libjpeg.so

libpng12.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libpng12.so.0

libpng12.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libpng12.so.0

libpng12.so.0 (libc6) => /lib/i386-linux-gnu/libpng12.so.0

libpng12.so.0 (libc6) => /usr/lib/i386-linux-gnu/libpng12.so.0

libpng12.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libpng12.so

**Comment by lieblb** [comment]
Ich würde mal sagen, die libGD 2.1.1 vs. libGD 2.1.0 ist ein heißer Kandidat.

**Comment by lieblb** [comment]
Hängt irgendwie mit der image interpolation zusammen. Beheben lässt sich bei mir der Fehler z.B. in `ilScanAssessmentGDWrapper::rotate` durch diese Änderung:

```
        imagesetinterpolation($this->getImage(), IMG_NEAREST_NEIGHBOUR);
	$rotated = imagerotate($this->getImage(), $rad, $white);
```

Ich probiere noch weiter.

**Comment by lieblb** [comment]
Muss mit den GD-Änderungen in `src/gd_interpolation.c` zu tun haben (bzw. mit dem Nichtvorhandensein derer in GD 2.1.0). Mit `IMG_NEAREST_NEIGHBOUR` und `IMG_BICUBIC` geht's, aber mit `IMG_BILINEAR_FIXED`,  was auch der default ist, geht es schief.

**Comment by gvollbach** [comment]
Ok, spannend ich bin halt nur etwas verwundert, wie hoch die Abweichung ist, aber das hängt wahrscheinlich dann mit der Bildgröße zusammen. Aber wenn das die Behebung der Problems ist sollten wir die Option zur Interpolation setzen.

**Comment by lieblb** [comment]
Ich hab jetzt mal ein bisschen rumgedifft. Also: GD 2.1.0 und GD 2.1.1 haben nur ein paar Änderungen in der Image-Skalierung. Jetzt ist aber "GD 2.1.0 bundled", das mit `with-gd` ins PHP kompiliert wird, wieder was ganz anderes als GD 2.1.0; das eine liegt im PHP-Repo, und ist voller Änderungen gegenüber der offiziellen GD 2.1.0. Trotzdem habe ich die eine Änderung, die das auslöst, leider nicht gefunden. Aber es muss irgendein verändertes Verhalten bei der Rotation oder Skalierung sein. Ich hätte nur gern einen Anhaltspunkt gefunden, wieso es gerade bei `IMG_BILINEAR_FIXED` passiert. Aber nun, immerhin haben wir einen Fix. Ich suche trotzdem noch ein wenig weiter.

**Comment by gvollbach** [comment]
War hier jetzt eigentlich noch was offen, oder kann ich hier zu machen.

**Comment by lieblb** [comment]
Können wir schließen.

**Comment by gvollbach** [comment]
Ok.
