### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by bogenschlag** [DatabayAG/ScanAssessment#2]
I tried to install the plugin on 5.1 test ILIAS, but 

> 4. Search the ScanAssessment plugin in the list of plugin and choose Activate from the Actions drop down.

lead to the following error:

`in_array() expects parameter 2 to be array, null given`

`ilias.log` shows:

`[deqol] [2017-01-30 16:34:15.053324] Uni_Stuttgart_root.WARNING: ::{closure}:50 PHP Error: in_array() expects parameter 2 to be array, null given in /srv/www/vhosts/ilias3.uni-stuttgart.de/Services/Database/classes/class.ilDB.php on line 1289`

**Comment by gvollbach** [comment]
Please make a "git pull" there was a wrong type in an update step which was thankfully fixed with the pull request from  @lieblb

**Comment by bogenschlag** [comment]
Will do, thanks!
