### ISSUE TITLE
Call to a member function getPosition() on a non-object

### ISSUE THREAD

**Issue by lieblb** [DatabayAG/ScanAssessment#20]
Nach dem neuesten Update tritt bei bestehenden Scans ein Fehler auf, der auch sporadisch auftaucht, wenn Scans nicht den exportierten PDFs entsprechen.

Es handelt sich um folgenden Fehler:

```Fatal error: Call to a member function getPosition() on a non-object in /var/www/html/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/ScanAssessment/classes/scanner/class.ilScanAssessmentScanProcess.php on line 137```

In diesem Fall wird leider auch das `scan_assessment.lock` nicht gelöscht, man muss es händisch entfernen.

Debug-Export (die importierten Scans, bei denen obiger Fehler auftritt, sind `scan1.jpg` und `scan2.jpg`):

[scasExport.zip](https://github.com/DatabayAG/ScanAssessment/files/854202/scasExport.zip)

**UPDATE** Das Problem tritt nur bei `scan2.jpg` auf.

**Comment by gvollbach** [comment]
Das liegt aber nicht zufälligerweise an #23 oder?

**Comment by lieblb** [comment]
Ich denke nicht, weil bei `jpg` soweit ich weiß keine palettierten Bilder möglich sind.

**Comment by gvollbach** [comment]
Ok, dann werde ich mir den Export auch nochmal genauer anschauen.

**Comment by lieblb** [comment]
Logs und Debug-Export für diesen Fehler im `unstable` Branch:

[scasExport.zip](https://github.com/DatabayAG/ScanAssessment/files/878982/scasExport.zip)

[apache-log.txt](https://github.com/DatabayAG/ScanAssessment/files/878983/apache-log.txt)

[scan-log.txt](https://github.com/DatabayAG/ScanAssessment/files/878984/scan-log.txt)

**Comment by gvollbach** [comment]
Danke, werde ich mir direkt anschauen.

**Comment by gvollbach** [comment]
Mh, jetzt bin ich etwas verwirrt, haben sie noch lokale Patches oder die Grenzwerte angepasst? Weil ich hab hier lokal kein Problem, bei ihnen scheint es aber ja bei keinem Bild bis überhaupt zur Antworterkennung zu kommen oder hatten sie die "answer_detection" und "qr"  und "test_marker" Bilder gelöscht?

Beispielbild:
![29_1_answer_detection](https://cloud.githubusercontent.com/assets/10603233/24455846/55ddf868-1491-11e7-9b4e-d058a8c2daa3.gif)

**Comment by lieblb** [comment]
Also das versteh ich jetzt auch nicht. Gelöscht hab ich nix. Ich hab's auch grad nochmal frisch laufen lassen und bekomme dasselbe Ergebnis. Hier mein Setup:

```
root@d29ebb2217db:/var/www/html/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/ScanAssessment# git status
On branch unstable
Your branch is up-to-date with 'upstream/unstable'.
```

<img width="1043" alt="settings" src="https://cloud.githubusercontent.com/assets/25431384/24457265/fb40e7d0-1495-11e7-9a20-5f3a8e064f03.png">

Ich schaue mal, ob ich's selbst hier debuggen kann.

**Comment by gvollbach** [comment]
Eine Sache ist mir noch aufgefallen, es scheint teilweise Probleme mit PHP7 und Imagemagick zu geben, zumindest hab ich die hier lokal. Ich hatte es jetzt noch nicht weiter untersucht. Aber vielleicht ist das hier auch der Fall, können sie mal bitte in der "Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/ScanAssessment/libs/php-qrcode-detector-decoder/lib/QrReader.php"
 `$isUseImagickIfAvailable = false;`
oben im Konstruktor eintragen.

**Comment by lieblb** [comment]
Ok, ich hab hier offenbar ein nicht zum PDF-Export passendes Import-Set verwendet. Ich mach das nochmal komplett neu.

Der konkrete `getPosition()`-Fehler im Moment entsteht, weil, wenn der QR-Code nicht gelesen werden kann, ein `$false` in die Crop-Funktion kommt.

Hab einen Fix unter https://github.com/DatabayAG/ScanAssessment/pull/26.

**Comment by gvollbach** [comment]
Ok, fix ist übernommen, ich hab dann auch mal die Deaktivierung von imagemagick in dem QRCodeReader committed. Ich lasse hier aber trotzdem noch mal offen, falls das noch mal bei ihnen auftreten sollte.

**Comment by lieblb** [comment]
Habe jetzt das Blatt mit dem einen problematischen QR-Code isoliert. Hier ist es:

![qr-code-error-scan](https://cloud.githubusercontent.com/assets/25431384/24461351/13f0faf8-14a1-11e7-9604-8aa7e1f36bb7.png)

Die erzeugten tmp/rescaled.png und tmp/new_file.png sind dann:

**rescaled.png:**

![rescaled](https://cloud.githubusercontent.com/assets/25431384/24461365/22c08c2e-14a1-11e7-90c9-59279c1dcaac.png)

**new_file.png:**

![new_file](https://cloud.githubusercontent.com/assets/25431384/24461360/1b20ea86-14a1-11e7-85ad-3e1ffc4e25fd.png)

Wertet man nun dieses `new_file.png` isoliert mit dem QR-Decoder aus, also:

```
	public function analyse()
	{
        $path = '/var/ilias/data/ilias/scanAssessment/tst_269/scans/tmp/new_file.png';
        $qr	= new ilScanAssessmentQrCode($path);
        $qr_pos	= $qr->getQRPosition();
        $this->log->info('qr pos: ' . var_export($qr_pos, true));
        return;
```

dann bekommt man als Ergebnis `INFO (6): qr pos: false`.

**Comment by gvollbach** [comment]
Ja ich weiß das die 29 bei ihnen das "Problemblatt" war, deswegen hab ich das ja auch oben in meinem Beitrag genutzt, bei mir lies sich das ja scannen und auch der QR Code wurde richtig erkannt.

**Comment by gvollbach** [comment]
Ich hab gerade noch einen Grenzfall gefunden und behoben, ich gehe davon aus, das jetzt auch bei ihnen das PDF 29 funktionieren sollte.

**Comment by lieblb** [comment]
Ja, tatsächlich, funktioniert jetzt. Weil das hier so unregelmäßig vom Rand weg ist, oder? Klappt jedenfalls jetzt.

**Comment by gvollbach** [comment]
Nicht ganz, es wird geprüft ob der QRCode freisteht vor dem Ausschneiden, in ihrem Beispiel ist allerdings zuwenig Rand rechts übrig, sprich es lief da über das Bild hinaus beim gegenprüfen der Grauwerte und die waren somit immer 0. Der Code wurde also schon gefunden, aber die Code Logik dachte hier in dem Fall er steht halt nicht frei, daher wurde dann die Suche abgebrochen. Ich denke dann haben wir hier zumindest jetzt auch alles durch.
