### ISSUE TITLE
Offset in der Scan Answer Detection

### ISSUE THREAD

**Issue by lieblb** [DatabayAG/ScanAssessment#3]
Möglicherweise ist dies noch dem Entwicklungszustand geschuldet, in jedem Falle geht bei meinen Versuchen hier die Erkennung der Checkboxen schief, da sie an der falschen Stelle verortet werden:

![22_1_answer_detection](https://cloud.githubusercontent.com/assets/25431384/22464169/c2722732-e7b5-11e6-919c-a425bc1e4a61.jpg)

Hier ein Paket mit ILIAS-Test und gescanntem JPEG, der das nachvollziehbar machen sollte:

[scanassessment-answer-detection.zip](https://github.com/DatabayAG/ScanAssessment/files/741889/scanassessment-answer-detection.zip)

**Comment by gvollbach** [comment]
Das liegt an der Stelle eher an der rudimentären Fehlerkorrektur. Die sind auch nicht auf der falschen Seite, sondern die Drehung welche in dem Dokument ist wird noch nicht herausgerechnet.
Das steht an der Stelle noch auf dem Programm, das Drehungen im Scan besser erkannt werden und korrigiert werden. 

An dieser Stelle aber auch nochmal danke für den Pull Request.

**Comment by gvollbach** [comment]
Ich habe jetzt gerade noch mal in den Code geschaut und es Drehungen werden eigentlich schon korrigiert. Und ich kann mir diese Abweichung nicht wirklich erklären, können sie mir mal bitte das Logfile zur Verfügung stellen, welches im Externen Datenverzeichnis von Ilias liegt?

**Comment by lieblb** [comment]
Das müsste das hier sein:

[scan.txt](https://github.com/DatabayAG/ScanAssessment/files/742030/scan.txt)

**Comment by gvollbach** [comment]
Ja das war es, ich hab einen Theorie, kann es sein das ihr Drucker nochmal einen Seitenrand einfügt und damit den Inhalt skaliert?

**Comment by lieblb** [comment]
Das wäre schon möglich.

**Comment by gvollbach** [comment]
Wäre an der Stelle die plausibelste Erklärung. Das ist an der Stelle allerdings noch nicht berücksichtigt, da muss ich mal schauen wie ich das detektieren kann und dann einsprechend die Antwortpositionen korrigieren kann.

**Comment by lieblb** [comment]
Ich habe jetzt mal zwecks Debugging versucht, sämtliche Ränder beim Drucken zu deaktivieren, aber so richtig passt das hier immer noch nicht:

![3_1_answer_detection](https://cloud.githubusercontent.com/assets/25431384/22470473/baf47b58-e7cf-11e6-8019-ef67540a529a.jpg)

**Comment by gvollbach** [comment]
Ja aber wir kommen näher, ein Versatz scheint an der Stelle immer noch zu sein, ich bin gerade dabei das entsprechend zu detektieren und zu Überlegen wie ich das am besten korrigieren kann, erkennnen kann ich es zumindest jetzt schon mal.

**Comment by gvollbach** [comment]
So ich hab da jetzt mal ein paar Stellen umgebaut und angepasst in der Hoffnung, das die Fehlerkorrektur jetzt an der Stelle besser funktioniert. Bitte einmal gegen testen, ob das Problem hier damit auch abgefangen wird.

**Comment by lieblb** [comment]
Kann bestätigen, dass das mit der aktuellen Version (07878a7) jetzt auch mit Rändern bei uns funktioniert:

[testcase_20170202.zip](https://github.com/DatabayAG/ScanAssessment/files/747959/testcase_20170202.zip)

War mir zwischenzeitlich nicht sicher, ob ich mit der richtigen Version testete. Wäre es eine Idee, in den die Logs bei jedem Scan eine interne ScanAssessment-Plugin-Build-Version auszugeben?

**Comment by gvollbach** [comment]
Ah super. Danke für die schnelle Rückmeldung.

Könnte ich machen, allerdings bin ich mir nicht sicher ob das Zielführend wäre, da ich die Plugin Version eigentlich nur anpassen, wenn DB Updates oder Kontrollstruktur neu geladen werden muss, weniger bei einzelnen Commits. Aber die Commit ID wäre an der Stelle das was man eigentlich bräuchte.
