### ISSUE TITLE
Justierung der Schwellwertberechnung

### ISSUE THREAD

**Issue by lieblb** [DatabayAG/ScanAssessment#30]
Grundlage meines Tests folgender Debug-Export:

[scasExport.zip](https://github.com/DatabayAG/ScanAssessment/files/915959/scasExport.zip)

Gearbeitet wurde hier mit folgenden (Standard)schwellwerten:

<img width="666" alt="schwellwerte" src="https://cloud.githubusercontent.com/assets/25431384/24949506/2764a7ce-1f6e-11e7-9eda-2e65fe96bb31.png">

Leider werden dann etwa 50% der Fälle die Checkboxen nicht als angekreuzt erkannt, z.B.:

Fragencheckboxen auf Seite 69
Spalte 1 Matrikellnummer Seite 69
Fragencheckboxen 1 und 2 auf Seite 71
Spalte 3 Matrikellnummer Seite 71
Fragencheckboxen 1 und 2 auf Seite 70
Mehrere Spalten Martikelnummer Seite 70

Das Probieren verschiedener Schwellenwerte führt bei diesem konkreten Setup zu einem guten Ergebnis bei einem Schwellenwert von 0.4:

Matrikelnummer p.70; 0.45

<img width="470" alt="matrikelnummer p 70 0 45" src="https://cloud.githubusercontent.com/assets/25431384/24951334/53081efa-1f74-11e7-82f7-60bf49e5ab21.png">

Matrikelnummer p.70; 0.35

<img width="465" alt="matrikelnummer p 70 0 35" src="https://cloud.githubusercontent.com/assets/25431384/24951343/59b2a23e-1f74-11e7-9bbd-b0c3ed0e9691.png">

Matrikelnummer p.70; 0.4

<img width="466" alt="matrikelnummer p 70 0 4" src="https://cloud.githubusercontent.com/assets/25431384/24951349/5f98978a-1f74-11e7-9166-67883e893059.png">

Insgesamt geht es hier also um 0.05 hin oder her. Ob dies wirklich so praxistauglich ist, steht für mich gerade noch in Frage. Tatsächlich scheint die Einbeziehung des je nach Scanner unterschiedlichen geformten Checkboxrands einen erheblichen Unsicherheitsfaktor in die Berechnung zu bringen.

**Comment by gvollbach** [comment]
Sie müssen mir hier einmal auf die Sprünge helfen, sind die Bilder jetzt mit oder ohne den Code aus dem Pull Request entstanden?

**Comment by lieblb** [comment]
Die Bilder sind ohne den PR entstanden. Auffallend ist dort eben, dass beim Schwellenwert 0.45 etliche angekreuzte Checkboxen nicht erkannt wurden, bei 0.35 hingegen schon etliche leere Checkboxen als volle Checkboxen erkannt wurden. Das hat mich dann dazu gebracht, mit dem PR zu probieren, den Rand, der teilweise stark variiert, nicht in die Grauwertflächenberechnung zu ziehen.

**Comment by gvollbach** [comment]
Ah ok, dann verstehe ich auch die Ergebnisse, da mit dem rausrechnen des schwarzen Randes das dritte Bild der Serie nicht wirklich Sinn ergeben würde. Ist das Problem denn dann mit dem PR genug minimiert, oder soll ich mir das dann auch noch mal genauer anschauen?

**Comment by lieblb** [comment]
Ich denke mit dem PR ist es jetzt ganz gut, ich glaube, man kann damit arbeiten.

**Comment by gvollbach** [comment]
Ok, super dann hier auch nochmal ein Dankeschön für ihre Arbeit.
