### ISSUE TITLE
Löschen von bereits hochgeladenen Dateien

### ISSUE THREAD

**Issue by lieblb** [DatabayAG/ScanAssessment#34]
Es muss eine Möglichkeit geben, bereits hochgeladene, aber noch nicht analysierte Dateien, zu löschen. Konkret sind wir auf der Testplattform in einen Zustand gelaufen, in dem wir weder vor noch zurück können, ohne auf den Server zu gehen:

<img width="1040" alt="nicht-analysierte-dateien" src="https://cloud.githubusercontent.com/assets/25431384/25423146/c8da4ec4-2a63-11e7-9987-719f0597a08f.png">

**Comment by gvollbach** [comment]
Werde ich mir mal noch anschauen, ansonsten hab ich gerade noch einen Bug an der Stelle gefixt, beim zweiten Bild schlägt aber wohl die Markerdetektion fehl, warum muss ich mir nochmal anschauen.

**Comment by gvollbach** [comment]
Löschen von "nicht analysierten Dateien" ist jetzt möglich.

**Comment by gvollbach** [comment]
Ok, hab das Problem gefunden, aber ich verstehe es um ehrlich zu sein nicht so ganz
`if($region->size() > 0.1 * dx * dy)`
ist eigentlich nicht korrekt eigentlich müsste das
`if($region->size() > 0.1 * $dx * $dy)`
sein, aber dann schlägt die Detektion bei dem image2.png fehl.

**Comment by lieblb** [comment]
Oje, das ist natürlich falsch. Eine Besonderheit bei image2.jpg ist, dass da eine voll ausgefüllte Checkbox ist. Ich schau mir das morgen an.

**Comment by gvollbach** [comment]
Ok super.

**Comment by lieblb** [comment]
Wenn ich das richtig sehe, funktioniert aber die Detektion für image2.png jetzt. Auch lokal klappt ein ähnlicher Testfall mit voll ausgefüllten Checkboxen. Ich rätsle eigentlich nur noch, wie der obige Code unter PHP 7 jemals funktionieren konnte.

**Comment by gvollbach** [comment]
Ja das funktioniert jetzt weil ich wieder den Ursprungscode eingefügt habe, sprich
`if($region->size() > 0.1 * dx * dy)`
Dann bedeutet das in PHP aber soviel wie 
`if($region->size() > 0)`
und ich bin mir da nicht sicher ob das wirklich die Intention des Codes war.

**Comment by lieblb** [comment]
Die Idee war nur, zu verhindern, dass irgendein kleiner Tintenpatzer, der nicht der Marker ist, für den Marker gehalten wird, indem man die Größe prüft.

Ich hab's bis jetzt nicht geschafft, das Problem mit image2 auf dem Testsystem lokal nachzustellen, da brauche ich glaube ich ein paar Tricks.

Eine bessere Version von obigem Code wäre wohl dies:

```
                    // make sure we got the actual marker and not some random dirt by checking
                    // the overall size, according to the bounding box, is reasonable.
                    $bbox = $region->bbox();
                    if($bbox !== false)
                    {
                        list($minX, $minY, $maxX, $maxY) = $bbox;

                        if($maxX - $minX > 0.5 * $dx && $maxY - $minY > 0.5 * $dy)
                        {
                            $len2 = sqrt($dx * $dx + $dy * $dy);
                            return new ilScanAssessmentVector($region->centre(), $len2);
                        }
                    }
```

**Comment by gvollbach** [comment]
`$this->log->debug(sprintf('Found Region (%s) is not large enough (%s), dx (%s), dy (%s), we are at %s/%s.', $region->size(), 0.1 * $dx * $dy, $dx, $dy, $region->centre()->getX(), $region->centre()->getY()));`

Found Region (3) is not large enough (162), dx (36), dy (45), we are at 131/143.  
Found Region (3) is not large enough (162), dx (36), dy (45), we are at 127/138.  
Found Region (3) is not large enough (162), dx (36), dy (45), we are at 123/133.  
Found Region (3) is not large enough (162), dx (36), dy (45), we are at 119/128.  
Found Region (3) is not large enough (162), dx (36), dy (45), we are at 117/125.  
Found Region (3) is not large enough (162), dx (36), dy (45), we are at 115/123.  
Found Region (3) is not large enough (162), dx (36), dy (45), we are at 111/118.  
Found Region (3) is not large enough (162), dx (36), dy (45), we are at 107/113.  
Found Region (3) is not large enough (162), dx (36), dy (45), we are at 103/108.  
Found Region (3) is not large enough (162), dx (36), dy (45), we are at 99/103.  
Found Region (3) is not large enough (162), dx (36), dy (45), we are at 95/98.  
Found Region (3) is not large enough (162), dx (36), dy (45), we are at 91/93.  
Found Region (3) is not large enough (162), dx (36), dy (45), we are at 87/88.  
Found Region (3) is not large enough (162), dx (36), dy (45), we are at 83/83.

**Comment by lieblb** [comment]
Hm... könnte glatt ein Problem im flood fill sein, dadurch dass über `ilScanAssessmentPoint` mglw. float Koordinaten kommen.

Ändert ein `intval` in `ilScanAssessmentRegion` etwas?

```
    public function __construct($image, $p, $threshold)
    {
        // essentially a flood fill that detects all black marker pixels.

        $x = intval($p->getX());
        $y = intval($p->getY());
```

**Comment by gvollbach** [comment]
Nein ändert hier leider nichts.

**Comment by lieblb** [comment]
Ich bin ein bißchen ratlos, was da passiert.

Hab noch weitere Debugausgaben eingebaut:

https://github.com/DatabayAG/ScanAssessment/pull/39

**Comment by gvollbach** [comment]
Region at [131, 143] smaller than 162, details: region: size: 3, centre: [131, 143 ], pixels: array (
  '132/142' => true,
  '130/144' => true,
  '131/143' => true,
)  
Region at [127, 138] smaller than 162, details: region: size: 3, centre: [127, 138 ], pixels: array (
  '128/137' => true,
  '126/139' => true,
  '127/138' => true,
)  
Region at [123, 133] smaller than 162, details: region: size: 3, centre: [123, 133 ], pixels: array (
  '124/132' => true,
  '122/134' => true,
  '123/133' => true,
)  
Region at [119, 128] smaller than 162, details: region: size: 3, centre: [119, 128 ], pixels: array (
  '120/127' => true,
  '118/129' => true,
  '119/128' => true,
)  
Region at [116, 125] smaller than 162, details: region: size: 3, centre: [116, 125 ], pixels: array (
  '117/124' => true,
  '115/126' => true,
  '116/125' => true,
)  
Region at [115, 123] smaller than 162, details: region: size: 3, centre: [115, 123 ], pixels: array (
  '116/122' => true,
  '114/124' => true,
  '115/123' => true,
)  
Region at [111, 118] smaller than 162, details: region: size: 3, centre: [111, 118 ], pixels: array (
  '112/117' => true,
  '110/119' => true,
  '111/118' => true,
)  
Region at [107, 113] smaller than 162, details: region: size: 3, centre: [107, 113 ], pixels: array (
  '108/112' => true,
  '106/114' => true,
  '107/113' => true,
)  
Region at [103, 108] smaller than 162, details: region: size: 3, centre: [103, 108 ], pixels: array (
  '104/107' => true,
  '102/109' => true,
  '103/108' => true,
)  
Region at [99, 103] smaller than 162, details: region: size: 3, centre: [99, 103 ], pixels: array (
  '100/102' => true,
  '98/104' => true,
  '99/103' => true,
)  
Region at [95, 98] smaller than 162, details: region: size: 3, centre: [95, 98 ], pixels: array (
  '96/97' => true,
  '94/99' => true,
  '95/98' => true,
)  
Region at [91, 93] smaller than 162, details: region: size: 3, centre: [91, 93 ], pixels: array (
  '92/92' => true,
  '90/94' => true,
  '91/93' => true,
)  
Region at [87, 88] smaller than 162, details: region: size: 3, centre: [87, 88 ], pixels: array (
  '88/87' => true,
  '86/89' => true,
  '87/88' => true,
)  
Region at [83, 83] smaller than 162, details: region: size: 3, centre: [83, 83 ], pixels: array (
  '84/82' => true,
  '82/84' => true,
  '83/83' => true,
)  
Probing found nothing trying to rotate...  
  Could not detect Marker!  
Marker detection done.  
Marker not found retrying after cropping...  
Starting marker detection...  
Top Left Marker found Start[0, 373], End[22, 399] starting to detect exact position.  
Estimated marker position [11, 386], size: [22, 26]  
Region at [11, 387] smaller than 57.2, details: region: size: 21, centre: [10.333333333333, 389.19047619048 ], pixels: array (
  '12/388' => true,
  '12/389' => true,
  '12/390' => true,
  '11/390' => true,
  '11/389' => true,
  '11/391' => true,
  '10/391' => true,
) [too many pixels]

**Comment by lieblb** [comment]
Wie es für mich jetzt aussieht, ist das Problem, dass nach dem ersten Rotieren mit einem Bild gearbeitet wird, auf dem die Debug-Linien eingezeichnet wurden:

![rotate_file](https://cloud.githubusercontent.com/assets/25431384/25521395/a8f3f266-2bff-11e7-8893-2c6040a61bbb.png)

Das führt am Ende dann zu den seltsamen 3-Pixel Regionen: das sind die schrägen blauen Linien links oben.

Die Analyse scheint zu funktionieren, wenn ich `ilScanAssessmentScanner::isDebug()` auf `false` setze.

Soweit ich das verstehe, sollten `image` und `tempImage` wohl immer unterschiedlich sein, sind sie aber nicht?

**Comment by gvollbach** [comment]
Ok Tatsache, da scheint was durcheinander zu kommen. Schau ich mir nachher nochmal an.

**Comment by gvollbach** [comment]
Ok Fehler gefunden, jetzt läuft auch das "Problembild" auch im debug Modus durch.
