### ISSUE TITLE
Sammeldownload ZIP kaputt?

### ISSUE THREAD

**Issue by lieblb** [DatabayAG/ScanAssessment#35]
Der Sammeldownload als ZIP scheint nicht zu funktionieren. Wählt man ihn aus, und geht dann auf "PDFs herunterladen" wird trotzdem kein ZIP herunterladen. Die Auswahlbox springt wieder auf "Fahne".

<img width="774" alt="sammeldownload-zip" src="https://cloud.githubusercontent.com/assets/25431384/25423234/30808282-2a64-11e7-920e-bd5f3b2efaa5.png">

**Comment by gvollbach** [comment]
Wie haben sie das denn versucht? Weil ich hab es gerade mal ausprobiert und ich bekomme ein zip. Gedacht ist hier eigentlich in der Checkbox die Alternative auswählen und dann auch "PDFs herunterladen" klicken.
[complete.zip](https://github.com/DatabayAG/ScanAssessment/files/957594/complete.zip)

**Comment by lieblb** [comment]
Das muss vorhin bei mir ein Browserproblem gewesen sein.

**Comment by lieblb** [comment]
Das Problem scheint dann aufzutreten, wenn noch gar keine PDFs erzeugt wurden. D.h.  wenn keine PDFs da sind (oder wenn man "Delete all PDFs" gemacht hat), und dann auf das Downloadformat ZIP geht, und dann "Download PDFs" macht, dann wird kein ZIP runtergeladen, sondern die PDFs werden erzeugt. Erst wenn man dann  nochmal ZIP auswählt und "Download PDFs" macht, erhält man das ZIP.

**Comment by gvollbach** [comment]
Moment wenn noch keine PDFs erzeugt wurden, heißt der Button auch nur "PDFs generieren" dann wird auch kein Download gestartet wenn man in der Select Box Fahne ausgewählt hat.

**Comment by lieblb** [comment]
Ach so, verstehe, dann ist das ein Bedienungsproblem. In diesem Fall ist also die Auswahl des Menüs irrelevant. Sollte es vielleicht dann gar nicht angezeigt/ausgegraut werden?

**Comment by gvollbach** [comment]
Wenn sie der Meinung sind das es die Sache noch mal verdeutlichen würde, kann ich das natürlich auch noch entfernen oder disablen.

**Comment by lieblb** [comment]
Das wäre schon schön.

**Comment by gvollbach** [comment]
Done. Selectbox ist jetzt disabled, wenn noch keine PDFs existieren.
