### ISSUE TITLE
Bogenmanagement bzgl. unbekannter Teilnehmerzahl

### ISSUE THREAD

**Issue by lieblb** [DatabayAG/ScanAssessment#36]
Bei Prüfungen ist die exakte Teilnehmerzahl oftmals nicht genau im Vorhinein bekannt. Es können daher folgende Konstellationen auftreten:

(A) Es werden initial zu wenige Bögen erstellt. Wie können wir weitere Bögen erstellen ohne die bereits erstellten wegwerfen zu müssen?

(B) Es werden initial zu viele Bögen erstellt. Wie können wir bereits erstellte Bögen nachträglich löschen, so dass die Revision ohne deren Scaneingabe ablaufen kann?

**Comment by gvollbach** [comment]
(A) ist aktuell nicht vorgesehen, ich könnte mir hier aber noch eine Erweiterung vorstellen.
(B) Ist eigentlich kein Problem, da nicht alle Bögen benötigt werden, die Daten auch in mehreren Iterationen an Ilias zurückgeführt werden.

**Comment by gvollbach** [comment]
(A) wurde implementiert.

**Comment by lieblb** [comment]
Das funktioniert jetzt gut. Sollte "created pdfs" nicht vielleicht nach Dateiname sortiert sein?

**Comment by gvollbach** [comment]
Done.
