### ISSUE TITLE
Datum des Assessments sollte mglw. kein Pflichtfeld sein

### ISSUE THREAD

**Issue by lieblb** [DatabayAG/ScanAssessment#37]
Momentan ist das Datum des Scanklausur-Assessments ein Pflichtfeld. Dies erscheint uns nach einem internen Review nicht sinnvoll, da wir diese Angabe in den allermeisten Fällen nicht benötigen oder leer lassen würden. Auch das aktuelle Datum wäre wenig hilfreich, da es sich ja dann um das Erstellungsdatum handeln würde. Ist der Umstand, dass das Datum ein Pflichtfeld ist, ausschließlich der Idee geschuldet, die Papierbögen hinsichtlich einer Archivierung klar von inhaltsgleichen Prüfungen anderer Semester unterschieden zu können?

**Comment by gvollbach** [comment]
Um ehrlich zu sein hab ich hier keine wirkliche Präferenz, wenn sie mir hier sagen, sie hätten gerne ein Möglichkeit kein Datum angeben zu können, dann kann ich das gerne anpassen.

**Comment by gvollbach** [comment]
Feld kann jetzt auch leer gelassen werden, dann wird kein Datum gedruckt in den PDFs.
