### ISSUE TITLE
Fehler bei Rückführung

### ISSUE THREAD

**Issue by lieblb** [DatabayAG/ScanAssessment#38]
Wird eine Rückführung durchgeführt, ohne dass alle PDFs einem Benutzer zuordnet werden, bricht die Rückführung mit einem Fehler ab (auf dem Testsystem so passiert gegen 10:40).

Die vorhandenen Benutzer werden in den Test rückgeführt, die nicht vorhandenen nicht; d.h. im Test ist danach ein unvollständiges Ergebnis.

Ist es möglich, die Rückführung immer dann anzubieten, wenn im Test noch keine Teilnehmer sind (und nicht, wenn sie schon einmal durchgeführt wurde)? Wir hatten jetzt konkret das Problem, dass wir durch den Fehler oben die Rückführung zweimal machten, dann im Test die Teilnehmer, weil alles doppelt war, löschten, und dann aber nicht nochmal die Rückführung anstoßen konnten. So hatten wir dann keine Möglichkeit mehr, die Ergebnisse in den Test zu bekommen.

**Comment by gvollbach** [comment]
Um ehrlich zu sein hab ich den Fehler jetzt noch nicht so ganz verstanden, die Rückführung ohne vollständige Nutzerzuordnung sollte eigentlich funktionieren, was war denn die Fehlermeldung?

Den anderen Punkt kann ich mir mal anschauen.

**Comment by gvollbach** [comment]
Es gibt jetzt einen Button mit dem etwas sperrigen Namen "Ergebnisrückführung zurücksetzen" welcher den Status zurücksetzt und einen weitere Rückführung ermöglicht.

**Comment by lieblb** [comment]
Das ist klasse.

Der ursprüngliche Fehler war einfach eine ILIAS-Exception mit einem dieser kryptischen ILIAS-Fehlercodes, die dann ein gleichbenamtes Logfile erzeugen.

**Comment by gvollbach** [comment]
Ok, werde ich mir noch einmal anschauen, das sollte eigentlich nicht sein, aber erklärt warum ich im ScanAssessment Log nicht gefunden habe, das muss dann ein Ilias Fehler gewesen sein.

**Comment by gvollbach** [comment]
Fixed in git.
