### ISSUE TITLE
Syntaxfehler

### ISSUE THREAD

**Issue by bogenschlag** [DatabayAG/ScanAssessment#4]
Nach erfolgreicher Installation habe ich einen Test angelegt. Wenn ich dort auf *Scanklausur* klicke, kommt der folgende Fehler:

`Parse error: syntax error, unexpected '[' in /srv/www/vhosts/ilias3.uni-stuttgart.de/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/ScanAssessment/classes/scanner/imageWrapper/class.ilScanAssessmentGDWrapper.php on line 252`

**Comment by bogenschlag** [comment]
Das ging schnell, danke! 😊

**Comment by gvollbach** [comment]
Da habt ihr aber ne sehr angestaubte PHP Version. Hab die Aufrufe durch array() Aufrufe ersetzt. Sprich "git pull" was mich aber wundert das der Fehler kam wenn du in das Plugin klickst und nicht wenn du Scans wieder analisierst.

**Comment by bogenschlag** [comment]
SLES 11 SP3, was soll ich sagen. 🤷🏼‍♂️

Aber für ILIAS 5.2 kriege ich dann SLES-12-VMs mit PHP7 … 😌

**Comment by bogenschlag** [comment]
Tut jetzt!

**Comment by gvollbach** [comment]
Super. Dann mach ich hier mal wieder zu.
