### ISSUE TITLE
Ignorierung der Shuffle-Einstellung bei Antworten?

### ISSUE THREAD

**Issue by lieblb** [DatabayAG/ScanAssessment#41]
Es scheint so, dass die Antworten im Antwortbogen immer genau in der Reihenfolge ausgegeben werden, in der sie in der Single-/Multiple-Choice-Frage definiert wurden, d.h. die Einstellung "Antworten mischen" (`-shuffle_answers-`) in den Fragen wird offenbar vollständig ignoriert. Ist man nur mein Eindruck oder ist das momentan wirklich so?

**Comment by gvollbach** [comment]
Um ehrlich zu sein muss ich das an der Stelle selber einmal gegenprüfen. Die Antworten werde eigentlich über die Ilias eigenen Funktionen geholt. 
Aber nur damit wir nicht an einander vorbeireden, sie meinen wirklich das Setting "Antwort mischen" in der Frage und nicht die Randomisierung pro Teilnehmer in dem Scanklausur Plugin?

**Comment by lieblb** [comment]
Ja genau, ich meine das Mischen der Reihenfolge der Antworten innerhalb einer Frage, also nicht das Randomisieren der Reihenfolge der Fragen insgesamt.

**Comment by gvollbach** [comment]
Fixed.
