### ISSUE TITLE
Vertikaler Versatz bei Antwortbögen

### ISSUE THREAD

**Issue by lieblb** [DatabayAG/ScanAssessment#42]
Werden die Antworten nicht inline, sondern als Bogen ausgegeben, gibt es zwischen Checkbox und Antwortnummer einen vertikalen Versatz, der recht verwirrend sein kann (insbesondere sichtbar bei den jeweils unteren Antwort, also z.B. 1d und 7d):

<img width="222" alt="versatz" src="https://cloud.githubusercontent.com/assets/25431384/25666781/ca3b8e0e-3021-11e7-92f8-39c75cb08a83.png">

**Comment by gvollbach** [comment]
Fixed.
