### ISSUE TITLE
Revision bei Antwortbögen

### ISSUE THREAD

**Issue by lieblb** [DatabayAG/ScanAssessment#43]
Die Revision von Antworten mit Antwortbögen gestaltet sich momentan zumindest sehr umständlich, da der Korrektor die kodierte Antwortnummer (z.B. 1b) und auf der anderen Seite, bei der Erkennung unten, die aufgelöste Antwort (im Beispiel hier 78) sieht:

<img width="918" alt="revision-antwortbogen" src="https://cloud.githubusercontent.com/assets/25431384/25836871/a753bed0-348a-11e7-8524-9419b70b7ceb.png">

Die notwendige Information zur Korrektur wäre hier der entsprechende Zuordnungsschlüssel, der auf dem Frageblatt für die entsprechende Frage steht, im konkreten Beispiel (1a) 56, (1b) 78, (1c) 15, (1d) 12. Diese Information bekommt der Korrektur momentan nur durch Suchen des für den Teilnehmer ausgedruckten Fragebogens, was enorm aufwendig ist. Könnte man hier nicht die entsprechende Zuordnung jeweils bei der Revision mitanzeigen?

**Comment by gvollbach** [comment]
Nur damit ich jetzt die Frage richtig verstanden habe, sie hätten gerne das dort statt der 56, 78... steht (1a) 56, (1b) 78... steht?

**Comment by lieblb** [comment]
Ja genau, damit man sieht, ob denn die automatische Erkennung tatsächlich mit der im Bild visualisierten Checkboxmarkerierung übereinstimmt.

**Comment by gvollbach** [comment]
Ok dann hatte ich das richtig verstanden, ist committed, funktioniert allerdings dann nur bei neu erzeugten PDF, da ich die Bezeichner jetzt erst mitspeicher.
