### ISSUE TITLE
Hochladen von gelöschten PDFs erzeugt keinen Fehler

### ISSUE THREAD

**Issue by lieblb** [DatabayAG/ScanAssessment#44]
Wird ein PDF hochgeladen und analysiert, das nicht (mehr) aktuell ist (d.h. aus einem vorherigen PDF-Erzeugungs-Durchlauf stammte, inzwischen aber gelöscht wurde und durch PDFs aus einem weiteren PDF-Erzeugungs-Durchlauf "ersetzt" wurde) hochgeladen, kommt kein Fehler; stattdessen werden die Dateien verarbeitet, `rescaled` wird angelegt, jedoch keine `answer_detection` o.ä.:

<img width="1153" alt="files" src="https://cloud.githubusercontent.com/assets/25431384/25849993/ede8b13a-34c0-11e7-91c2-de434523d3d2.png">

Hier wäre eine Fehlermeldung, dass das PDF nicht (mehr) aktuell ist, sehr hilfreich.

**Comment by gvollbach** [comment]
Ja das ein rescaled erzeugt wird ist klar, es wird ja die Detektion angestoßen um unter anderem die PDF Id zu detektieren, wenn dann festgestellt wird, das dieses PDF nicht mehr aktuell ist, wird die Detektion abgebrochen, daher keine Answer Detektion, die Antwort Daten sind dann aus der Datenbank in dem Moment ja schon nicht mehr vorhanden. Ich muss mal gegenprüfen im Log müsste das eigentlich schon erwähnt werden.

**Comment by gvollbach** [comment]
Ok im Log stand es sowieso schon und eine Info-Anzeige gab es eigentlich auch schon, die wurde nur durch das Refactoring ausgehebelt, sollte jetzt wieder wie gedacht funktionieren.
