### ISSUE TITLE
Fehler beim Rückspielen von Testergebnissen

### ISSUE THREAD

**Issue by lieblb** [DatabayAG/ScanAssessment#49]
Habe hier gerade einen Test, bei dem das Rückspielen eines Teilnehmers auf einen Fehler läuft:

[04b05_9148.txt](https://github.com/DatabayAG/ScanAssessment/files/989923/04b05_9148.txt)

Offenbar fehlt im entsprechenden XML ein `active_fi`. Ich bin mir grade nicht sicher, wie man das debuggen kann, bzw. wo ich überhaupt das XML finden könnte, das da importiert wird?

**Comment by gvollbach** [comment]
Das ist das gleiche Problem wie hier #38, ich bin hier aber auch noch nicht dazu gekommen das weiter zu debuggen.

> Ich bin mir grade nicht sicher, wie man das debuggen kann, bzw. wo ich überhaupt das XML finden könnte, das da importiert wird?

`ScanAssessment/classes/controller/class.ilScanAssessmentReturnDataGUI.php`
Zeile 86: unlink($xml_file); auskommentieren.

**Comment by lieblb** [comment]
Das Problem ist vielleicht, dass ich hier einfach ein Rückspielen anstosse, obwohl ich gar nicht alle Teilnehmer zugewiesen habe:

<img width="773" alt="ruckspielen" src="https://cloud.githubusercontent.com/assets/25431384/25902728/acdc354c-359a-11e7-924f-ab8cbc0ab32e.png">

Schau ich mir das XML an, so ist nur die `test_id` für `118` definiert, alle anderen, die hier als `active_fi` auftauchen, gibt es wegen fehlender Zuordnung in `tst_active` gar nicht:

[results.xml.zip](https://github.com/DatabayAG/ScanAssessment/files/990002/results.xml.zip)

Also eigentlich ein Fall für eine Fehlermeldung? Oder wo man das Rückspielen gar nicht erlauben sollte? Ich frage mich gerade, was ich mache, wenn ich rückspielen will/muss, aber einen Teilnehmer nicht zuordnen kann. Dann lieber doch das Rückspielen für alle anderen ermöglichen, denke ich mir.

**Comment by gvollbach** [comment]
Ah ok, nein das übertragen der Ergebnisse sollte auch möglich sein wenn nicht alle zugeordnet sind, das Problem wird hier in der Tat sein, das beim Export auch die "Ergebnisse" drin sind für welche noch gar keine Revision abgeschlossen wurde, das sollte nicht sein.

**Comment by gvollbach** [comment]
Fixed in git.
