### ISSUE TITLE
Interner Fehler bei nicht zu Export passendem Import

### ISSUE THREAD

**Issue by lieblb** [DatabayAG/ScanAssessment#5]
Wird ein nicht zum exportierten PDF passendes gescanntes JPEG hochgeladen, kommt ein interner Fehler:

Fatal error: Call to a member function getPosition() on a non-object in /var/www/html/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/ScanAssessment/classes/scanner/class.ilScanAssessmentScanProcess.php on line 78

Offenbar ist bei ```$x1        = $marker[0]->getPosition()->getX();``` der Wert von ```$marker[0]```nicht belegt.

Wünschenswert wäre hier natürlich eine richtige Fehlermeldung, wie: Ihr Import passt nicht zum Export.

Der Fehler taucht offenbar auf, wenn in einer ILIAS-Instanz ein JPEG importiert wird, das aus einem PDF hervorgeht, das nie in dieser Instanz exportiert wurde.

**Comment by gvollbach** [comment]
Ja das wird teilweise schon abgefangen, wenn jpeg hochgeladen werden, welche zu einem anderen Test gehören, hier schlägt die Erkennung der Marker fehl, da das jpeg höchstwahrscheinlich keine hat. Werde ich noch abfangen.

**Comment by gvollbach** [comment]
Wenn dort jetzt Dateien ohne Markierungen hochgeladen werden, sollte das jetzt auch entsprechend als Info Nachricht angezeigt werden, das in den Dateien keine Marker gefunden wurden.
