### ISSUE TITLE
Häufiger Vertikaler Versatz bei Erkennung

### ISSUE THREAD

**Issue by lieblb** [DatabayAG/ScanAssessment#52]
Bei unserem ersten größeren Pilottest wurden leider ca. 25% aller Seiten nicht erkannt und zwar offenbar wegen eines vertikalen Versatzes in der vermuteten Y-Position der Checkboxen:

![versatz1](https://cloud.githubusercontent.com/assets/25431384/26409368/b3221708-40a0-11e7-98c2-76d40002d7e4.png)

![versatz2](https://cloud.githubusercontent.com/assets/25431384/26409370/b599931c-40a0-11e7-9661-eb9ad8ff2c4f.png)

**Detaillierte Testdaten**

[testfall.zip](https://github.com/DatabayAG/ScanAssessment/files/1025949/testfall.zip)

**Comment by lieblb** [comment]
Das gesamte Testset, das nur eine Erkennungsrate von ca. 75% ausweist:

[testset.zip](https://github.com/DatabayAG/ScanAssessment/files/1031102/testset.zip)

**Comment by gvollbach** [comment]
Schau ich mir an, danke für die Rückmeldung. Ach so können sie mir bitte noch die Logdatei von dem Tag anhängen?

**Comment by gvollbach** [comment]
Ich hab gerade mal was committed, wäre super wenn sie das mal gegentesten könnten.

**Comment by lieblb** [comment]
Ihre letzte Änderung ist eine deutliche Verbesserung, und senkt die Fehlerquote zumindest für die Fragencheckboxen (die Matrikelnummern habe ich mir noch nicht angesehen) und zumindest in diesem Testset auf ca. 10%, was, wenn sich das auch in weiteren Tests bestätigt, ein Erfolg wäre. Was mich etwas skeptisch macht, ist, dass es leider immer noch drei Seiten (46/2, 50/1 und 51/1) gibt, bei denen es genau um eine Checkbox vertikal verschoben ist, ohne dass dafür ein Grund erkennbar wäre:

46/2:
![46_2_answer_detection](https://cloud.githubusercontent.com/assets/25431384/26828488/f465f344-4ac1-11e7-8b0e-6d3a4a118ad8.png)

50/1:
![50_1_answer_detection](https://cloud.githubusercontent.com/assets/25431384/26828493/f835b676-4ac1-11e7-9a70-44f9a59cfa4d.png)

51/1:
![51_1_answer_detection](https://cloud.githubusercontent.com/assets/25431384/26828499/fc00a356-4ac1-11e7-9303-8e9c896b1457.png)

**Comment by gvollbach** [comment]
Mh komisch, ein Problem mit 51/1 hab ich auch noch, aber die anderen beiden sehen bei mir so aus:

![answer_detection](https://cloud.githubusercontent.com/assets/10603233/26828976/fb0c444e-4ac3-11e7-9a14-9783e0206590.gif)

**Comment by lieblb** [comment]
Lassen Sie uns nochmal Logfiles für 50/1 vergleichen:

[50.1.log.zip](https://github.com/DatabayAG/ScanAssessment/files/1055180/50.1.log.zip)

Die Top und Bottom Marker detection sieht auch in meinem Log von den Positionen absolut richtig aus.

**Comment by gvollbach** [comment]
Hier bitte, ich habe aber gerade auch noch was anderes gefunden, ich muss nur nochmal verstehen was da genau hängt, scheint wieder mit den Debug Modus zu tun zu haben, also den im Zweifel mal deaktivieren, also in `classes/scanner/class.ilScanAssessmentScanner.php`
[50.1.txt.zip](https://github.com/DatabayAG/ScanAssessment/files/1055207/50.1.txt.zip)

**Comment by lieblb** [comment]
Ja, Problem bei 50/1 verschwindet wenn ich `$debug = false` setze.

**Comment by lieblb** [comment]
Bei 46/2 ist das Problem ohne `$debug` auch weg.

**Comment by gvollbach** [comment]
Ja es scheint irgendein Verweis falsch zu laufen, aber ich konnte ihn bisher noch nicht isolieren, es scheint was mit dem `rotate` Aufruf zu tun, da scheint gerade irgendwie ein temp Bild drinnen zu sein und das haut dann bei wiederholter Markerdetektion die `probing` Funktion raus. Das erklärt auf das vereinzelte auftreten, nur wenn wir halt in `if($rotated == false && abs($rad) > 0.05)` reinlaufen.

**Comment by lieblb** [comment]
OK, den rotate hatte ich auch im Verdacht. Ich frage mich ob `new_file` und `rotate_file` nicht eindeutige IDs bekommen könnten oder ob man nicht ganz darauf verzichten könnte; mir scheint das ein ziemliches Dickicht zu sein.

**Comment by gvollbach** [comment]
So ich glaub ich hab das Problem gefunden, hatte nur indirekt mit der rotate Funktion zu tun, lag an der falschen Verwendung des Temp Images (welches zum drauf zeichnen benutzt wird) statt dem normalen Image (auf welches eigentlich nur lesend zugegriffen werden soll). 
Was aber vor der rotate Funktion nicht auffällt, da dort noch nicht im Bild gezeichnet wurde, wenn dann allerdings nach der Rotation wieder in `getMarkerPosition` gesprungen wird, dann ist dort was drauf gezeichnet und das bringt dann die Markerdetektion durcheinander.

Die laufen jetzt bei mir alle durch, gibt zwar noch ein paar Ausreißer in der Erkennung, das liegt aber dann an schlecht gesetzten Kreuzen oder der kompletten unkenntlich machen der Checkboxen z.B. 51/1 Frage 2 Antwort 4.

**Comment by lieblb** [comment]
Die eine Checkbox ist wirklich ein Sonderfall; ansonsten liegt aber mit meinen Schwellwerten die Erkennungsrate für die Fragecheckboxen dieses Testsets jetzt bei 100%.

<img width="779" alt="bildschirmfoto 2017-06-07 um 11 31 37" src="https://user-images.githubusercontent.com/25431384/26871873-f0bf8288-4b74-11e7-9027-dc165fa3fed4.png">

**Comment by gvollbach** [comment]
Das klingt doch schon mal viel versprechend.
Sie können wenn es nach mir geht gerne solche dinge wie ihre Einstellungen welche sie gerade hier gepostet haben auch gerne in das Wiki einstellen. Ich denke es schadet nie dort mal Einstellungen von verschiedenen Institutionen zu haben und vielleicht auch mal Best Practices zu sammeln.

Dann kann ich hier zu machen oder?

**Comment by lieblb** [comment]
Ja, ok, ich mach einen neuen Issue auf, falls bei dem zweiten TestSet, das ich noch testen will, etwas passieren sollte.

**Comment by lieblb** [comment]
Wie kommt man denn auf das Wiki?

**Comment by gvollbach** [comment]
Klingt nach einem Plan. 

Einfach hier auf Github:
![untitled](https://user-images.githubusercontent.com/10603233/26872803-222e876c-4b78-11e7-9c38-2ec36d4d0b41.png)
Dort sollten sie eigentlich Zugriff drauf haben als eingeloggrer Nutzer, dann haben wir nämlich auf alles direkt zusammen.
