### ISSUE TITLE
Fehlerhafte Anzeige in Revision bei Mehrfachimport 

### ISSUE THREAD

**Issue by lieblb** [DatabayAG/ScanAssessment#53]
Irgendwas geht bei der Revisionsanzeige schief, wenn man dieselbe Seite mehrfach importiert und analysiert.

Im vorliegenden Fall habe ich Seite 50 aus #52 mehrfach importiert und analysiert. In der Revision sieht das dann so aus:

<img width="626" alt="bildschirmfoto 2017-06-07 um 07 44 53" src="https://user-images.githubusercontent.com/25431384/26863846-4e580778-4b55-11e7-9cc7-fcb432b6f148.png">

Was schief ist, ist dass hier **59** Checkboxen angezeigt werden. Auf Seite 50/1 sind 5 Fragen, auf Seite 50/2 sind 6 Fragen, das ergibt 44 Checkboxen (jede Frage hat 4 Checkboxen). Selbst wenn ich jetzt noch die 8 Matrikelcheckboxen dazurechne (werden die hier überhaupt mit angezeigt?) komme ich auf 52 statt auf 59.

**Comment by gvollbach** [comment]
> Matrikelcheckboxen ...  (werden die hier überhaupt mit angezeigt?)

Nein die werden nur bei der Zuordnung angezeigt.
Werde ich mir anschauen, können sie bitte mal im `ILIAS/www/data/CLIENT/scanAssessment` im entprechenden Unterorder die Dateien auflisten?

**Comment by gvollbach** [comment]
Es wurde bei den Checkboxen bisher noch nicht aufgeräumt beim erneuten einscannen, sollte jetzt funktionieren, wenn sie eine neue Seite einscannen, das Layout hab ich dort auch noch mal etwas angepasst.
