### ISSUE TITLE
Weitere Erkennungsprobleme

### ISSUE THREAD

**Issue by lieblb** [DatabayAG/ScanAssessment#55]
Leider gibt es mit einem TestSet neue Erkennungsprobleme, die wieder offenbar wegen eines vertikalen Versatzes entstehen.

TestSet ist wie folgt:

[URK-Scan-20170607.tif.zip](https://github.com/DatabayAG/ScanAssessment/files/1060210/URK-Scan-20170607.tif.zip)
[1495636590__0__tst_269.zip](https://github.com/DatabayAG/ScanAssessment/files/1060211/1495636590__0__tst_269.zip)

Teilweise erhebliche Fehler entstehen bei folgenden Seiten:

23/1
31/2
63/2
14/1
14/2
24/1
24/2
60/2
61/2
64/2

Zum Teil ist dies auch der Größe der Markierungen in diesem TestSet geschuldet. Um dieses separate Problem zu beheben hätte ich mit https://github.com/DatabayAG/ScanAssessment/pull/54 einen Vorschlag für eine Änderung in der Feinerkennung, die zumindest die letzten 7 der obigen Seiten bis auf eine Checkbox korrekt erkennt.

Es bleiben in jedem Falle aber

23/1
31/2
63/2

Um zu sehen, was hier schief läuft, habe ich die Boundingboxen ohne Feinverarbeitung ausgeben lassen. Wie man im folgenden sieht, ist leider der vertikale Versatz so groß, dass die Feinerkennung mit einer BBox startet, die keinerlei Überschneidung mit der tatsächlichen Checkbox hat. In Folge kommt es zu einer Fehlerkennung.

23/1:

![23_1_answer_detection](https://user-images.githubusercontent.com/25431384/26917134-57f1f02c-4c2d-11e7-83df-98a4c8296885.png)

31/2:

![31_2_answer_detection](https://user-images.githubusercontent.com/25431384/26917146-6b6a9302-4c2d-11e7-9ee5-c09baa49eb59.png)

63/2:

![63_2_answer_detection](https://user-images.githubusercontent.com/25431384/26917151-71000edc-4c2d-11e7-9eda-d2b1ef1228ff.png)

In den anderen Fällen, die der neue PR behebt, ist der Versatz klein genug, so dass noch eine Überschneidung da ist, und die Feinerkennung das beheben kann. Bei den drei Fällen hier ist aber der Versatz offenbar einfach zu groß. Grundsätzlich scheint mir, dass das vertikale Versatzproblem die Wurzel alles Übels in der Erkennungsgenauigkeit ist.

**Comment by gvollbach** [comment]
Ok werde ich mir anschauen, das Problem sollte doch auch noch lösbar sein.

**Comment by gvollbach** [comment]
Sollte nicht mehr auftreten.
