### ISSUE TITLE
Vertikale Position der Checkboxen in der Groberkennung falsch

### ISSUE THREAD

**Issue by lieblb** [DatabayAG/ScanAssessment#57]
Nach einigem Überlegen glaube ich nun, dass wir mit der gesamten Feinerkennung furchtbar auf dem Holzweg sind. Das Grundproblem ist ein Fehler in der Ermittlung der vertikalen Position der Checkboxen in der markerbasierten Berechnung. Klappt diese, ist gar keine Feinerkennung mehr notwendig.

Die Feinerkennung ist aus meiner Sicht momentan ein Hack um einen Bug in der markerbasierten Berechnung der Checkboxen.

Denn die markerbasierte Berechnung klappt für die horizontale Position der Checkbox bis auf, in den schlechtesten Fällen, ca. 10%; was, denke ich, noch akzeptabel ist, weil dies dann den tatsächlichen Grauwert der Checkbox um maximal 10% verfälscht, was bei geeigneten Schwellenwerten eine gerade noch akzeptierbare Grenze sein könnte. Für die vertikale Position klappt sie aber gar nicht, hier sind wir in aller Regel > 20%. Durch diesen vertikalen Fehler entsteht überhaupt erst das Problem einer Nachjustierung bei Feinerkennung.

Die folgenden Daten entstanden auf dem bekannten Testset:

[testset.zip](https://github.com/DatabayAG/ScanAssessment/files/1067327/testset.zip)

Die Feinerkennung in `ilScanAssessmentCheckBoxElement `wurde komplett abgeschaltet:

<img width="423" alt="code_change" src="https://user-images.githubusercontent.com/25431384/27023140-88894bd2-4f51-11e7-9db7-acef929e05cb.png">

Nun kann man den Versatz der ermittelten zur tatsächlichen Checkboxposition ermitteln, so wie im folgenden Bild mit dem roten Pfeil für die vertikale Position exemplarisch dargestellt:

![versatzmessung](https://user-images.githubusercontent.com/25431384/27023179-b3de0160-4f51-11e7-9bd0-e9cde1688b64.png)

Macht man dies für die ca. 60 Seiten im obigen Testset, erhält man folgende Daten:

[versatz.xlsx](https://github.com/DatabayAG/ScanAssessment/files/1067331/versatz.xlsx)

Als Histogramm visualisiert ergibt sich folgendes:

![versatz-prozent](https://user-images.githubusercontent.com/25431384/27023218-db30673a-4f51-11e7-9f5b-5cf611797c60.png)

Blau ist der horizontale Versatz, gelb der vertikale. Der Versatz ist in Prozent angegeben, 100% vertikaler Versatz bedeutet also, dass die vermutete Position genau am unteren Rand der tatsächlichen anfängt, 50% bedeutet, genau in der Mitte. 0% bedeutet, es passt genau. 

Es muss möglich sein, mit dem vertikalen Fehler in den Bereich des horizontalen Fehlers zu bekommen. Damit sollte eine brauchbare Erkennungsgenauigkeit gegeben sein.

**Comment by gvollbach** [comment]
Erstmal danke für die Daten und Auswertung. 
Ja ich glaube ich werde da auch nochmal etwas essentiell Umbauen müssen, da mir auch die Kopplung in der `analyseImage` nicht gefällt. Was meiner Meinung nach auch für #55 verantwortlich ist.

**Comment by gvollbach** [comment]
Sollte behoben sein.
