### ISSUE TITLE
Markerdetection bei Translation

### ISSUE THREAD

**Issue by lieblb** [DatabayAG/ScanAssessment#6]
Mir macht die Markererkennung noch Sorge; ich weiß, dass hier noch gar nicht alles implementiert ist, was ja den Fehlermeldungen zu entnehmen ist, möchte aber zumindest mal darauf hinweisen, dass bei Seiten, die zwar nicht gedreht, aber leicht versetzt sind, also keinen vollkommen regelmäßigen Rand auf allen vier Seiten aufweisen, die Markererkennung leider weiterhin fehlschlägt.

Ich mal aus einer Vorlage (vgl. `vorlage.pdf` im anhängigen ZIP-File) zwei Scans derselben physikalischen Seite Papier gebaut, einen der sauber gescannt wurde (`perfect.jpg`), und einen, der einen minimalen Versatz hat (`imperfect.jpg`). Die Differenz dieser beiden Scans schaut so aus, es handelt sich also vor allem um eine Translation:

![diff](https://cloud.githubusercontent.com/assets/25431384/22644520/40478a74-ec63-11e6-9219-d8d19b46ec28.png)

Nun wird `perfect.jpg` sauber erkannt, aber bei `imperfect.jpg` passiert folgendes (und in der Folge kann der Scan nicht verarbeitet werden):

_1  | 17-02-06 10:27:24 DEBUG (7): Starting marker detection... 
web_1  | 17-02-06 10:27:24 DEBUG (7): Top Left Marker found Start[23, 32], End[32, 44] starting to detect exact position. 
web_1  | 17-02-06 10:27:24 DEBUG (7): Exact Top Left Marker found at [34.7, 32.6] with length 27. 
web_1  | 17-02-06 10:27:24 DEBUG (7): Bottom Left Marker found Start[21, 1326], End[33, 1311] starting to detect exact position. 
web_1  | 17-02-06 10:27:24 DEBUG (7): Exact Bottom Left Marker found at [33, 1323.3] with length 26.893121797218. 
web_1  | 17-02-06 10:27:24 DEBUG (7): Rotation (-0.075465072323372). 
web_1  | 17-02-06 10:27:24 DEBUG (7): Image seems to be rotated (-0.075465072323372). 
web_1  | 17-02-06 10:27:24 DEBUG (7): Probing found nothing trying to rotate... NEEDS IMPLEMENTAION 
web_1  | 17-02-06 10:27:24 DEBUG (7): Marker not found retrying with higher threshold. 
web_1  | 17-02-06 10:27:24 DEBUG (7): Probing found nothing trying to rotate... NEEDS IMPLEMENTAION 
web_1  | 17-02-06 10:27:24 WARN (4): Could not detect Marker! 
web_1  | 17-02-06 10:27:24 DEBUG (7): Marker detection done. 

[Dateien.zip](https://github.com/DatabayAG/ScanAssessment/files/754362/Dateien.zip)

**Comment by gvollbach** [comment]
Fehlt da was im Log, weil das sieht irgendwie komisch aus, da fehlt der rescaling Part, die Markerdetection sollte hier nicht fehlschlagen, wie sieht denn die test_marker.jpg bei dem "imperfect" aus. Die Logmeldung ist übrigens an der Stell nicht ganz korrekt, da geht es eigentlich ums drehen um 180 Grad. Normale Rotationen werden an der Stelle schon korrigiert werden. Mit der Translation kann ich noch mal schauen, sollte aber eigentlich kein Problem bereiten, gerade das wird mit dem Rescaling/Croppen korrigiert.

Spannend an der Stelle wäre auch noch die "rescaled.jpg" die hier wohl existieren sollte, ich vermute aktuell da wird zuviel weggeschnitten, was zu diesem Fehlverhalten führen kann.

**Comment by lieblb** [comment]
Hier ist das gesamte Logfile für imperfect.jpg:

[ilias.txt](https://github.com/DatabayAG/ScanAssessment/files/754659/ilias.txt)

In `iliasdata/scanAssessment/tst_xyz/scans/analyzed` werden auch gar keine Dateien erzeugt. In `iliasdata/scanAssessment/tst_xyz/scans/tmp` werden folgende Dateien erzeugt:

[test_tmp.zip](https://github.com/DatabayAG/ScanAssessment/files/754673/test_tmp.zip)

**Comment by gvollbach** [comment]
Ok, nach dem Log und dem Bild, die Bildqualität des Scans ist schon grenzwertig, da hilft es dann nicht wirklich das dort noch die Korrekturen drauf gemacht werden. Bitte mal mit mehr dpi den Scan austesten. Und aktuell wird die Dreh Korrektur halt bei einer Abweichung von 0.05 gemacht, vielleicht sollte man das noch etwas hochdrehen, bin ich mir hier gerade nicht sicher. Muss ich mal gegentesten.

**Comment by lieblb** [comment]
Das ist, soweit ich das von außen sehe, bei einer höheren Auflösung derselbe Effekt:

[imperfect_higher.jpg.zip](https://github.com/DatabayAG/ScanAssessment/files/754727/imperfect_higher.jpg.zip)

[20170206_ilScanAssessment.txt](https://github.com/DatabayAG/ScanAssessment/files/754728/20170206_ilScanAssessment.txt)

Hier die entsprechenden Dateien im tmp:

[tmp.zip](https://github.com/DatabayAG/ScanAssessment/files/754757/tmp.zip)

Was mir auffällt, ist dass die Dateien im tmp auch bei dieser Auflösung sehr unscharf/hoch komprimiert sind. 

Ich probier's nachher nochmal mit 600 dpi.

**Comment by gvollbach** [comment]
Ja ich vermute fast wir haben hier einen Grenzfall, aber ich werde mir das morgen noch mal im Detail an der Stelle anschauen.
Ich glaube nicht das sich hier mit einer noch höheren dpi Zahl sich was ändert.

Ja die werden im Moment beim schreiben stark komprimiert, ich glaub GD default ist hier ein JPEG Qualität von 75 ich werde die mal auf 100 stellen.

**Comment by lieblb** [comment]
Ich konnte das Problem mit 5 Scans bei 600 dpi nicht nachvollziehen. Mir scheint es bisher so, als tauche der Effekt dort nicht auf, auch bei offensichtlicher Rotation und Verschiebung nicht. Vorschlag: bei nicht gefundenen Markern eine Fehlermeldung, die auch vorschlägt, die dpi-Zahl zu erhöhen.

Mglw. teste ich noch mehr, aber momentan scheint mir dieser Issue damit geschlossen.

Ich habe leider im Zusammenhang mit den 600 dpi scans mehrere andere Probleme gefunden. Für zwei davon habe ich Issues geöffnet.

**Comment by gvollbach** [comment]
Ja das mag daran liegen, das sich mit den 600dpi auch die Abstände erhöhen, allerdings sehe ich es nicht wirklich als Praxistauglich an der Stelle mit 600dpi Scans zu arbeiten, da wird die Analyse pro Blatt 10-12 Sekunden dauern, grob geschätzt.
Ich werde mir heute mal die Marker Erkennung vornehmen, ich denke da lässt sich am meisten mit optimieren. Da von deren sauberen Detektion auch die Erkennung der Abweichungen vom Optimum erkennen lässt. Mir ist da gestern auch noch ein anderes Problem aufgefallen, was hier wahrscheinlich auch eine Ursache mit drinnen hat, nämlich das die Erkennung des unteren Linken Markers je nachdem wie stark die Seite nach rechts verschoben ist, am Marker sozusagen vorbei geht.

**Comment by gvollbach** [comment]
So ich hab mal die Erkennung etwas optimiert/entstaubt, sollte jetzt zumindest besser mit den Verschiebungen zurecht kommen, die Rotation steht aber noch aus, da muss ich nochmal ran. DEshabl lass ich jetzt hier mal noch offen.

**Comment by lieblb** [comment]
Mit der aktuellsten Version (ba4964988723f939cf11ac2a8df9533da05f8353, "now also with colors under php7") ist leider eine Regression eingetreten, so dass die Marker nun vertikal stark verschoben sind.

![extract](https://cloud.githubusercontent.com/assets/25431384/22877837/8ea48aae-f1d7-11e6-89e5-18f163d42f91.png)

[scan-plugin-20170213.zip](https://github.com/DatabayAG/ScanAssessment/files/770582/scan-plugin-20170213.zip)

**Comment by gvollbach** [comment]
Ok, werde ich mir anschauen.

**Comment by gvollbach** [comment]
Ich glaube das Problem gefunden zu haben, wäre super, wenn sie das mal gegentesten könnten.

**Comment by lieblb** [comment]
Das sieht jetzt weitaus besser aus. Ich konnte das Problem inzwischen auf die Änderungen bei 6666ebe isolieren. Hier mal die Übersicht der Ergebnisse (HEAD ist das erste):

c3f0391
![c3f0391](https://cloud.githubusercontent.com/assets/25431384/23064048/31548fe0-f50e-11e6-8b25-2005a3e57e91.png)

6666ebe
![6666ebe](https://cloud.githubusercontent.com/assets/25431384/23064032/23a5731e-f50e-11e6-9d92-c607fb5d4c40.png)

145a09c
![145a09c](https://cloud.githubusercontent.com/assets/25431384/23064041/2a32f788-f50e-11e6-9395-9d0388f5fb3e.png)

**Comment by gvollbach** [comment]
Ok, super. Ja das hatte ich dann auch gefunden, Hauptproblem war das hier:
`+		$x4 = 0;#$x2 - $marker_should_be_at_x;`
` +		$y4 = 0;#$a - $y2;`

Das hatte ich zeitweise auskommentiert, da sonst der QR Code je nachdem weggeschnitten wurde, hab das ganze jetzt noch was ausgebaut sollte also jetzt auch in Grenzfällen funktionieren.

**Comment by lieblb** [comment]
Leider gibt es immer noch erhebliche Probleme. Ich habe die aktuelle Version mal mit einem größeren 9-seitigen echten Test ausprobiert. Dabei stellt man nun fest, dass bei einigen Seiten die Erkennung sehr gut klappt, bei etwa 1/4 der Seiten aber weiterhin gar nicht. Hier zwei Beispiele. 

Gute Erkennung:

![good-1](https://cloud.githubusercontent.com/assets/25431384/23068408/d9db21c8-f523-11e6-9ed2-3229a0d44714.png)

Schlechte Erkennung:

![bad-8](https://cloud.githubusercontent.com/assets/25431384/23068424/eac7f1dc-f523-11e6-8099-865ae234fa59.png)

Das einzige was mir auffällt, ist, dass die Seite mit der schlechten Erkennung einen türkisen Spalt am rechten Rand hat. Sehen Sie irgendwas auffälliges in den Logfiles?

[logs.zip](https://github.com/DatabayAG/ScanAssessment/files/783387/logs.zip)

**Comment by gvollbach** [comment]
Der türkise Spalt kommt, wenn kleinere Drehungen ausgeglichen werden, das ist dann die Hintergrundfarbe. Ich hab beim einem meiner letzten commits mal einen Debug Export mit committed, der muss in der Plugin Konfiguration aktiviert werden, dann haben sie einen zusätzlichen Tab im dem ScanAssessment Plugin mit dem sie einen Export erzeugen können, das könnte helfen, ich hab zwar eine Vermutung aber da müsste ich erst noch was probieren.

**Comment by lieblb** [comment]
Das funktioniert, leider habe ich jetzt einen echten Test benutzt, den ich so nicht via Email rausgeben darf. Ich baue nächste Woche mal einen analogen Test, bei dem ich Ihnen das ganze Debug-Zip mal schicken kann.

**Comment by lieblb** [comment]
Hier wie angekündigt ein Link zu einem vollständigen Test-Debug-Export, wo leider z.T. erhebliche Verschiebungen zu finden sind (bei einigen Seiten die Ergebnisse aber auch wirklich gut sind):

http://myfiles.uni-regensburg.de/ssf/s/readFile/share/9636/-4892567088632639387/publicLink/scasExport-20170220-01.zip

scans/analysed/8/1/answer_detection.jpg
scans/analysed/10/1/answer_detection.jpg
scans/analysed/12/1/answer_detection.jpg
scans/analysed/14/1/answer_detection.jpg
scans/analysed/16/1/answer_detection.jpg

**Comment by gvollbach** [comment]
Ok, ich hab jetzt mal die Checkbox Detection noch etwas aufgebohrt. Vorweg Perfekt ist das auch noch nicht, ich werde da noch ein zwei Dinge ausprobieren müssen und die Matrikelnummer Verarbeitung muss noch angepasst werden, sprich die tut es gerade nicht. Aber es sollte zumindest in den meisten Fällen schon die Erkennung verbessern.
![answer_detection](https://cloud.githubusercontent.com/assets/10603233/23165999/10722204-f83f-11e6-9338-57bc0177ea8d.jpg)

**Comment by lieblb** [comment]
In der Tat sieht das jetzt bei den Fällen, wo es klappt, sehr gut aus. Bei den anderen Fällen treten jetzt immer Überlappungen wie unten auf, aber das wissen Sie wahrscheinlich.

<img width="295" alt="answers1" src="https://cloud.githubusercontent.com/assets/25431384/23215065/591c5330-f911-11e6-827d-2b2ea7853693.png">

<img width="291" alt="answers2" src="https://cloud.githubusercontent.com/assets/25431384/23215071/5c6d39be-f911-11e6-9a95-a4713e7bd0d4.png">

<img width="300" alt="answers3" src="https://cloud.githubusercontent.com/assets/25431384/23215076/5f1e1002-f911-11e6-96b5-d6de2dac231f.png">

**Comment by gvollbach** [comment]
Diese Überlappungen sollten eigentlich mit der aktuellsten Version von heute nicht mehr auftreten, sollte das doch der Fall sein, wäre ich hier wieder sehr an einem Export interessiert, oder sollten das noch Versionen vom alten Export sein, wäre die PDF Nummer davon interessant für mich.

**Comment by lieblb** [comment]
In der Tat, mit der aktuellsten Version stimmen alle Answer Boxes. Das sieht sehr ermutigend aus.

**Comment by gvollbach** [comment]
Ich will hier nicht ausschließen, das es hier nicht immer noch Grenzfälle gibt, bei denen es nicht funktioniert, aber dafür ist ja dann auch letzten Endes die Revision gedacht.

**Comment by lieblb** [comment]
Ja, diese Grenzfälle gibt es leider, doch sie scheinen, soweit ich das bisher getestet habe, nur dann aufzutreten, wenn das Kreuz erheblich die Checkbox verlässt, was ein Ausfüllungsfehler ist. Ich teste das noch weiter.

**Comment by gvollbach** [comment]
Ja ich denke es ist aktuell von der Erkennung relativ stabil. Aber Feedback in der Richtung ist immer super, dann kann ich nämlich schauen ob man da noch was optimieren kann.

**Comment by lieblb** [comment]
Dann, auch einfach zur Info, hier doch nochmal mein aktueller Testexport, wo ich bewusst schlampige Checkboxen gemacht habe:

http://myfiles.uni-regensburg.de/ssf/s/readFile/share/9695/5342886701081620701/publicLink/scasExport20170224.zip

Alle Bögen mit ordentlichen Checkboxen werden wunderbar erkannt.

Bei 52/Frage 3 führt das schlampige Kreuz dazu, dass die Checkboxen weiter rechts verortet werden als sie sind. Bei 54/Frage 2 und Frage 3 gibt es wohl ähnliche.

**Comment by gvollbach** [comment]
Interessant, können sie mir da mal das Logfile von hier anhängen, die bei 54 kann ich mir erklären, aber die komplett Verschiebung von allen auf 52 Frage 3 wundert mich.

**Comment by lieblb** [comment]
Hier das gesamte Logfile:

[20170224_ilScanAssessment.txt](https://github.com/DatabayAG/ScanAssessment/files/799320/20170224_ilScanAssessment.txt)

52 = URK-Scan-6-0.jpg

**Comment by gvollbach** [comment]
Ok, ich hab die Werte für die Erkennung mal noch etwas angepasst, jetzt wird zwar immer noch nicht das Kreuz bei PDF 52 richtig erkannt, aber die anderen Checkboxen passen jetzt zumindest.

**Comment by lieblb** [comment]
Nach zwei Tests mit der aktuellesten Version sieht es für mich nun so aus, dass die Erkennung in der jetzigen Form jetzt pilotfähig sein sollte. Da insbesondere auch Rotation und Translation in allen unseren Tests sauber erkannt wurden, würde ich sagen, wir können dieses Ticket schließen.

**Comment by gvollbach** [comment]
Ok, dann mach ich hier mal zu.
