### ISSUE TITLE
Mehrere Kreuze bei Single Choice werden trotzdem irgendwie bewertet.

### ISSUE THREAD

**Issue by GRRRR11** [DatabayAG/ScanAssessment#62]
Eins hab ich noch. Es geht darum, was passiert wenn die TN bei Single-Choice-Fragen zu viele Kreuze machen und das in der Revision nicht auffällt. Interessantes Phänomen:

Fall 1 (Sonderfall!): Bei einer Single-Choice-Frage mit 5 Antwortmöglichkeiten habe ich für vier der Antworten jeweils 1 Punkt, für eine Antwort 4 Punkte vergeben. Ein Student hat jetzt alle vier Antworten mit 1 Punkt angekreuzt und 4 Punkte für die Frage bekommen. Insgesamt müsste er 10 Punkte haben. Er hat 22 von 17 möglichen Punkten. Nimmt man in der Fragenrevision alle Häkchen bei der Frage weg, stimmt wieder alles.

Fall 2: Eine Studentin hat bei einer Single-Choice-Frage zwei Kreuze gemacht, die aber an der falschen Stelle. Zusätzlich hat sie sich den Scherz aus Fall 1 erlaubt. Sie dürfte eigentlich nur 8 Punkte haben, hat aber 20 von 17 möglichen Punkten. Nimmt man in der Fragenrevision alle Häkchen bei der Frage aus Fall 1 weg, stimmt wieder alles. ILIAS wertet die Frage mit den zwei Kreuzen an den falschen Stellen scheinbar mit 0 Punkten.

Fall 3: Ein Student hat bei einer Single-Choice-Frage zwei Kreuze gemacht, eines davon an der richtigen Stelle. Er hat ansonsten alles richtig, müsste also 17 Punkte haben. Die Auswertung ergibt 18 von 17 möglichen Punkten. ILIAS scheint die Frage mit den zwei Kreuzen mit 2 Punkten zu bewerten obwohl es nur einen Punkt geben kann.

Fall 4: Ein Student hat bei einer Frage alles angekreuzt, bei einer Frage zwei falsche Kreuze gemacht. Er hat am Ende 14 von 17 Punkten obwohl er nur 8 haben dürfte.

Da es in einer elektronischen Prüfung nicht vorkommen kann, dass bei einer Single-Choice-Frage mehr als eine Antwort angekreuzt wird, sollte es eine Funktion geben, die bei zu vielen Kreuzen die Frage automatisch mit 0 Punkten bewertet oder zumindest eine Warnung ausgibt.

**Comment by gvollbach** [comment]
Mh,

ja das kann durchaus sein, es werden hier bei der Analyse der Bilder halt erstmal nur die Markierungen gespeichert und dann nachher an Ilias weitergegeben. Da scheint Ilias intern keine Logik Prüfung zu sein. Am sinnvollsten wäre es wohl wenn man dann in der Antwort Revision einen Fehlerfall anzeigen würde, dann muss der Dozent hier entscheiden was er mit der Frage macht, ich schaue mir das nochmal an.

**Comment by gvollbach** [comment]
Ich hab jetzt mit mal zumindest eine Warnung implementiert, wenn bei einer Single Choice Frage mehr als eine Antwort angekreuzt ist. 
![untitled](https://user-images.githubusercontent.com/10603233/32945669-98ffda7a-cb94-11e7-86e6-03ba60ef1f88.jpg)

Aber hier müsste eh noch ein weitere Screen, der so allgemeine Logik Checks durchführt, hin. Aber das sehe ich eher in weiteren Version als jetzt hier in dem bugfix.
