### ISSUE TITLE
Formatierung der Klausur bei Antwortbögen

### ISSUE THREAD

**Issue by GRRRR11** [DatabayAG/ScanAssessment#63]
Wenn die Klasuur mit Antwortbögen geschrieben werden soll, stimmt die Formatierung an mehreren Stellen nicht so ganz:

1. Ist bei einer Single-Choice-Frage "mehrzeilige Anworten" eingestellt, sind auf den Bögen mit den Fragen die Antwortnummer und die zugehörige Antwort sehr verwirrend angeordnet:
![versatz_mehrzeilig](https://user-images.githubusercontent.com/33715246/33169980-e1105a40-d046-11e7-8b81-57a76fdc68a1.png)

1b. Allerdings nicht immer:
![versatz_mehrzeilig_2](https://user-images.githubusercontent.com/33715246/33169998-f4634260-d046-11e7-80bf-a86f9010e9ef.png)

2. Den Antwortbogen hat es ziemlich zerschossen:
![antwortbogen](https://user-images.githubusercontent.com/33715246/33170212-c7b7aaca-d047-11e7-9c8d-f38eed9cdf40.png)

Außerdem hat der Antwortbogen immer zwei Seiten, wobei die zweite Seite leer ist (bis auf QR-Code, Markierungen etc.).
Eine Klausur im Antwortbogen-Modus hat durch die Formatierungen und die zusätzliche Seite insgesamt 9 Seiten, wärend eine im Inline-Modus gerade einmal 4 Seiten hat.

Wird bei allen Fragen "einzeilige Antworten" eingestellt, gibt es auch bei der Formatierung des Antwortbogens keine Probleme mehr, allerdings wird weiterhin eine zweite ("leere") Seite ausgegeben.

[antwortbogen.pdf](https://github.com/DatabayAG/ScanAssessment/files/1498886/antwortbogen.pdf)

**Comment by gvollbach** [comment]
Hi,
ich vermute bei Punkt 1 sind paragraph tags das Problem, das ist auch im Lernmodul z.B. ein Problem gewesen.

Die zweite Leere Seite vermute ich hier auch mal entweder einen Überlauf, oder ein p tag der noch "gezeichnet" wird, sieht dann halt leer aus. Kannst du mir mal das zerschossene PDF und das Log dazu schicken. Und wie gesagt schau bitte mal bei den Mehrzeiligen Antworten mal, ob meine Vermutung da stimmt.

**Comment by GRRRR11** [comment]
Also bei den mehrzeiligen Antworten werden automatisch paragraph-tags gesetzt, das lässt sich irgendwie gar nicht verhindern. Ein Workaround wäre, die Frage erst als "mehrzeilig" zu schreiben, wegen der Übersichtlichkeit und dann vor dem Speichern in "einzeilig" zu ändern. Machen aber nicht alle Lehrenden mit.

**Comment by gvollbach** [comment]
Ja z.B. du hast halt bei mehrzeiligen Antworten dann direkt einen Tiny Editor, da kommen dann die p tags automatisch rein.

**Comment by gvollbach** [comment]
Ok wie erwartet aus deinem Log:
`Answer checkbox for Question with id 3519, answer order 2 and text <p>1989</p>`

**Comment by gvollbach** [comment]
Mal noch ne Frage zu Punkt 2, trat das bei allen auf oder nur bei dem? Und die zwei Seiten über den Layout Tab da vor gehangen?

Übrigens nette Idee, so Bilder zu inkludieren!

**Comment by GRRRR11** [comment]
Punkt 2 tritt immer auf sobald eine Frage mit mehrzeiligen Antworten dabei ist (also sobald die tags drin sind). Ob die zwei Seiten davor sind oder nicht spielt keine Rolle. 
Ich hab gerade mal vom TinyMCE auf den ILIAS-Seiteneditor umgestellt. Damit gibt es keine Probleme. Ich fürchte nur, dass sich dann wiederum die Prüfer über die eingeschränkten Formatierungsmöglichkeiten beschweren könnten. Aber das ist erstmal abzuwarten.

Da es zur Zeit ja nicht möglich ist, Bilder bei den Fragen direkt einzubinden ist das ein wenig aus der Not geboren, das über die Gestaltung zu machen. Wir werden im Januar mal bei einer echten Klausur testen, wie es ankommt.

**Comment by gvollbach** [comment]
Ok, danke für die Rückmeldung, dann schau ich mal ob ich das reproduziert bekomme.

**Comment by gvollbach** [comment]
Sag mal hast du das Shuffle pro User Setting aktiviert? Weil wenn ich das aktiviere hab ich genau den Effekt, wenn ich das wieder deaktiviere sind die PDFs wieder sauber. Muss mich mal auf die Suche begeben was da schief läuft.

**Comment by GRRRR11** [comment]
Passiert bei mir auch. Wenn die Randomisierung raus ist, wird der Antwortbogen ganz normal dargestellt.

Die leere Seite am Ende bleibt aber, egal was ich tue. Selbst wenn ich auf den ILIAS-Seiteneditor umstelle und sämtliche Tags rausnehme.

**Comment by gvollbach** [comment]
Ja das wird ein separates Problem sein, dann weiß ich aber zumindest das ich dort schon mal auf der richtigen Spur bin. Die Zusatz Seite sehe ich mir dann an, wenn das erste Problem eliminiert wurde.

**Comment by gvollbach** [comment]
Ich entferne jetzt p tags aus den Antworten. Sprich der erste Teil des Problems sollte jetzt behoben sein, das Problem mit dem Matrikelnummer Feld, war ein folge Problem, die Box war nämlich an der richtigen Stelle, der Rest des Headers war allerdings nach unten gedrückt.

Ich begebe mich dann mal jetzt auf die Suche woher die zusätzliche Seite am Ende kommt kommt.

**Comment by gvollbach** [comment]
Ok, die leere Seite war einfacher. Aber das erste werde ich mir wohl doch nochmal ansehen müssen, scheint noch nicht komplett gefixt zu sein.

**Comment by gvollbach** [comment]
So sollte jetzt definitiv nicht mehr auftreten.
