### ISSUE TITLE
Checkbox-Abdeckung zum Teil bei 2/3

### ISSUE THREAD

**Issue by lieblb** [DatabayAG/ScanAssessment#7]
Bei (teilweise verschobenen und leicht gedrehten) Scans mit 600 dpi ist die Abdeckung der tatsächlichen Checkbox im Bild durch die rechteckige Antwortmaske in einigen Fällen bei 2/3 der Fläche (vgl. z.B. unten das letzte Bild scan5, bei dem von der Checkbox nur 42 Pixel abgedeckt sind, 21 aber nicht). Insgesamt scheint mir dieser Wert unter der Annahme einer homogenen Grauwertberechnung in der Checkbox zwar möglicherweise gerade so ausreichend, gleichzeitig ist diese Abdeckung ja für uns das zentrale Gütekriterium der automatischen Auswertung, und, ohne weiter genauer darüber nachgedacht zu haben, ließen sich sicher Fälle konstruieren, in denen das verlorene Drittel den Schwellengrauwert auf die andere Seite von 0,5 zieht. Kurz gesagt wäre die Frage, ob hier noch Optionen bestehen, eine größere Abdeckung zu erzielen.

Hier die Abbildungen der Scans
![scan1](https://cloud.githubusercontent.com/assets/25431384/22656760/9a23c112-ec94-11e6-8dea-9f52a872bef3.png)
![scan2](https://cloud.githubusercontent.com/assets/25431384/22656763/9bd2ba40-ec94-11e6-9728-8b8457fc3602.png)
![scan3](https://cloud.githubusercontent.com/assets/25431384/22656765/9d047746-ec94-11e6-9e3a-6374823b2e6b.png)
![scan4](https://cloud.githubusercontent.com/assets/25431384/22656766/9e12a3e2-ec94-11e6-85ef-a82a47fb90a9.png)
![scan5](https://cloud.githubusercontent.com/assets/25431384/22656769/9f198bde-ec94-11e6-8a8c-8ec606e7e5cd.png)

Und hier die dazu passenden Logfiles:

[logs.zip](https://github.com/DatabayAG/ScanAssessment/files/755268/logs.zip)

**Comment by gvollbach** [comment]
Was mich hier eher wundert warum mich warum es hier einmal eine Verschiebung nach rechts und einmal nach links gibt? Waren das unterschiedliche Scans/Seiten? 
Ansonsten ist das eine Sache, welche mit einer Optimierung der Voranalyse und Korrektur der Quelldateien in den Griff zu bekommen sein sollte. Daher schließe ich den hier und wir machen bei #6 weiter, da ich dort auch eine Vermutung habe, warum die Marker Detektion Fehlschlägt, was mit einer Korrektur des Scanverhaltens für den unteren Marker einhergeht.
