### ISSUE TITLE
Seltsamer Abbruch bei 600 dpi scan

### ISSUE THREAD

**Issue by lieblb** [DatabayAG/ScanAssessment#8]
Vorweg: mein php memory limit und die execution runtime sind beide bei -1.

Bei einem bestimmten 600 dpi scan, bricht der Vorgang ab, aber kein rescaled.jpg wird erzeugt, und der scan_assessment.lock wird auch nicht gelöscht.

Hier das Log des betreffenden Scans:

[scan4.txt](https://github.com/DatabayAG/ScanAssessment/files/755265/scan4.txt)

Ich werde versuchen, eine mögliche Exception zu identifizieren, die hier irgendwo geworfen wird.

**Comment by gvollbach** [comment]
Ist das Logfile hier an der Stelle korrekt, hört das wirklich einfach dort auf? Weil dann muss irgendwo eigentlich was in einem Error Log stehen. Verstehe ich das richtig das das nur bei einer Datei der Fall war? Und das auch reproduzierbar?

**Comment by lieblb** [comment]
OK, ich konnte das Ding nun nochmal reproduzieren. Stellt sich als einer der Effekte heraus, wieso ich so ungern mit PHP arbeite.

Der Fehler war, dass in `imagecreatetruecolor` in `ilScanAssessmentGDWrapper::imageCropWithSource` sporadisch, aber je nach Ausführungszeit eben nicht immer, ein fataler time out geworfen wurde, obwohl die execution time auf -1 stand:

```Fatal error: Maximum execution time of -1 seconds exceeded in /var/www/html/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/ScanAssessment/classes/scanner/imageWrapper/class.ilScanAssessmentGDWrapper.php on line 307```

Execution time -1 bedeutet in meinem PHP 5.5.38 offenbar auch 30s. Whatever.

Kann man den ganzen Block in `ilScanAssessmentScanProcess::analyse` in einen `try-catch` packen?; momentan wird bei Exceptions ja leider gar nichts gelogged. Und neben Logging kann man dann auch bei Fehlern das scanassessment.lock sauber aufräumen. Soll ich einen PR stellen?

**Comment by gvollbach** [comment]
PR sind an der Stelle immer willkommen, von daher gerne. Sie können es ja auch zumindest sporadisch auslösen, von daher macht das an dieser Stelle sogar wohl mehr Sinn.

**Comment by gvollbach** [comment]
Sollte dank dem Pull Request erledigt sein.
